/* AUTO-GENERATED by scripts/generate-calculator-catalog.mjs — do not edit by hand */
import { calc, out } from "./helpers";
import type { SeedCalculator } from "../types";

export const generatedCatalog: SeedCalculator[] = [
  calc(
    "bmi",
    "Body Mass Index (BMI)",
    "anthropometry",
    "BMI = weight / height²",
    "Screening index for weight status using height and weight.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }],
    [out("BMI", "", "weight_kg / (height_cm / 100) ^ 2", 1)]
  ),
  calc(
    "bmr",
    "Basal Metabolic Rate (BMR)",
    "anthropometry",
    "Mifflin-St Jeor",
    "Estimated resting daily energy expenditure.",
    [{ shared: "age-years" }, { shared: "sex-mf" }, { shared: "height-cm" }, { shared: "weight-kg" }],
    [out("BMR", "kcal/day", "10 * weight_kg + 6.25 * height_cm - 5 * age + (sex == 1 ? 5 : -161)", 0)]
  ),
  calc(
    "tdee",
    "Total Daily Energy Expenditure",
    "anthropometry",
    "TDEE = BMR × activity",
    "Estimated daily calories including activity.",
    [{ shared: "age-years" }, { shared: "sex-mf" }, { shared: "height-cm" }, { shared: "weight-kg" }, { shared: "activity-factor" }],
    [out("TDEE", "kcal/day", "(10 * weight_kg + 6.25 * height_cm - 5 * age + (sex == 1 ? 5 : -161)) * activity", 0)]
  ),
  calc(
    "ideal-body-weight",
    "Ideal Body Weight",
    "anthropometry",
    "Devine equation",
    "Reference weight estimate based on height and sex.",
    [{ shared: "height-cm" }, { shared: "sex-mf" }],
    [out("Ideal weight", "kg", "(sex == 1 ? 50 : 45.5) + 2.3 * max(height_cm / 2.54 - 60, 0)", 1)]
  ),
  calc(
    "bsa",
    "Body Surface Area",
    "anthropometry",
    "Mosteller",
    "Surface area estimate used in dosing and physiology.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }],
    [out("BSA", "m²", "sqrt(height_cm * weight_kg / 3600)", 2)]
  ),
  calc(
    "body-fat",
    "Body Fat Percentage",
    "anthropometry",
    "US Navy method",
    "Body-fat estimate from circumference measurements.",
    [{ shared: "height-cm" }, { shared: "sex-mf" }, { shared: "waist-cm" }, { shared: "neck-cm" }, { shared: "hip-cm" }],
    [out("Body fat", "%", "(sex == 1 ? (86.01 * log10(waist_cm / 2.54 - neck_cm / 2.54) - 70.041 * log10(height_cm / 2.54) + 36.76) : (163.205 * log10(waist_cm / 2.54 + hip_cm / 2.54 - neck_cm / 2.54) - 97.684 * log10(height_cm / 2.54) - 78.387))", 1)]
  ),
  calc(
    "waist-to-height-ratio",
    "Waist-to-Height Ratio",
    "anthropometry",
    "WtHR = waist / height",
    "Central adiposity screening index.",
    [{ shared: "waist-cm" }, { shared: "height-cm" }],
    [out("WtHR", "", "waist_cm / height_cm", 2)]
  ),
  calc(
    "waist-hip-ratio",
    "Waist-to-Hip Ratio",
    "anthropometry",
    "WHR = waist / hip",
    "Fat distribution pattern estimate.",
    [{ shared: "waist-cm" }, { shared: "hip-cm" }],
    [out("WHR", "", "waist_cm / hip_cm", 2)]
  ),
  calc(
    "ponderal-index",
    "Ponderal Index",
    "anthropometry",
    "PI = weight / height³",
    "Alternative to BMI in some populations.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }],
    [out("Ponderal index", "kg/m³", "weight_kg / (height_cm / 100) ^ 3", 1)]
  ),
  calc(
    "adjusted-body-weight",
    "Adjusted Body Weight",
    "anthropometry",
    "AdjBW for obesity dosing",
    "Adjusted weight when actual BMI is elevated.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }, { key: "ideal_bw", label: "Ideal body weight (kg)", fieldType: "NUMBER", min: 40, max: 120, defaultValue: 70 }],
    [out("Adjusted BW", "kg", "ideal_bw + 0.4 * (weight_kg - ideal_bw)", 1)]
  ),
  calc(
    "lean-body-mass",
    "Lean Body Mass Estimate",
    "anthropometry",
    "Boer formula",
    "Estimated lean mass from height, weight, and sex.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }, { shared: "sex-mf" }],
    [out("Lean body mass", "kg", "sex == 1 ? (0.407 * weight_kg + 0.267 * height_cm - 19.2) : (0.252 * weight_kg + 0.473 * height_cm - 48.3)", 1)]
  ),
  calc(
    "body-adiposity-index",
    "Body Adiposity Index",
    "anthropometry",
    "BAI",
    "Hip circumference–based adiposity index.",
    [{ shared: "hip-cm" }, { shared: "height-cm" }],
    [out("BAI", "%", "100 * (hip_cm / (height_cm ^ 1.5)) - 18", 1)]
  ),
  calc(
    "bmi-prime",
    "BMI Prime",
    "anthropometry",
    "BMI / 25",
    "BMI relative to upper-normal reference (25).",
    [{ shared: "height-cm" }, { shared: "weight-kg" }],
    [out("BMI prime", "", "(weight_kg / (height_cm / 100) ^ 2) / 25", 2)]
  ),
  calc(
    "harris-benedict-bmr",
    "Harris-Benedict BMR",
    "anthropometry",
    "Classic Harris-Benedict",
    "Classic resting metabolic rate estimate.",
    [{ shared: "age-years" }, { shared: "sex-mf" }, { shared: "height-cm" }, { shared: "weight-kg" }],
    [out("BMR (HB)", "kcal/day", "sex == 1 ? (88.362 + 13.397 * weight_kg + 4.799 * height_cm - 5.677 * age) : (447.593 + 9.247 * weight_kg + 3.098 * height_cm - 4.330 * age)", 0)]
  ),
  calc(
    "fat-mass-index",
    "Fat Mass Index",
    "anthropometry",
    "FMI",
    "Fat mass normalized to height.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }, { shared: "sex-mf" }, { shared: "waist-cm" }, { shared: "neck-cm" }, { shared: "hip-cm" }],
    [out("Fat mass index", "kg/m²", "fat_pct / 100 * weight_kg / (height_cm / 100) ^ 2", 1)]
  ),
  calc(
    "target-weight-bmi",
    "Target Weight for BMI",
    "anthropometry",
    "Weight at target BMI",
    "Weight needed to reach a target BMI.",
    [{ shared: "height-cm" }, { key: "target_bmi", label: "Target BMI", fieldType: "NUMBER", min: 15, max: 35, defaultValue: 24 }],
    [out("Target weight", "kg", "target_bmi * (height_cm / 100) ^ 2", 1)]
  ),
  calc(
    "maintenance-calories",
    "Maintenance Calories",
    "anthropometry",
    "TDEE shortcut",
    "Quick maintenance calorie estimate from weight.",
    [{ shared: "weight-kg" }, { shared: "activity-factor" }],
    [out("Maintenance kcal", "kcal/day", "weight_kg * 24 * activity", 0)]
  ),
  calc(
    "body-weight-change",
    "Weekly Weight Change",
    "anthropometry",
    "Calorie balance",
    "Expected weekly weight change from daily calorie balance.",
    [{ key: "daily_balance", label: "Daily calorie balance (kcal)", fieldType: "NUMBER", min: -2000, max: 2000, defaultValue: -500 }],
    [out("Weekly change", "kg/week", "daily_balance * 7 / 7700", 2)]
  ),
  calc(
    "water-intake",
    "Daily Water Intake",
    "fitness-hydration",
    "35 mL/kg/day",
    "Hydration target based on body weight.",
    [{ shared: "weight-kg" }],
    [out("Daily water", "mL/day", "weight_kg * 35", 0), out("Daily water", "L/day", "weight_kg * 35 / 1000", 2)]
  ),
  calc(
    "target-heart-rate",
    "Target Heart Rate Zones",
    "fitness-hydration",
    "Karvonen",
    "Training zones using age and resting heart rate.",
    [{ shared: "age-years" }, { shared: "resting-hr" }],
    [out("Max HR", "bpm", "220 - age", 0), out("Moderate low", "bpm", "resting_hr + (220 - age - resting_hr) * 0.5", 0), out("Moderate high", "bpm", "resting_hr + (220 - age - resting_hr) * 0.7", 0)]
  ),
  calc(
    "max-heart-rate",
    "Maximum Heart Rate",
    "fitness-hydration",
    "220 − age",
    "Estimated maximum heart rate.",
    [{ shared: "age-years" }],
    [out("Max HR", "bpm", "220 - age", 0)]
  ),
  calc(
    "heart-rate-reserve",
    "Heart Rate Reserve",
    "fitness-hydration",
    "Karvonen HRR",
    "Heart rate reserve for training prescription.",
    [{ shared: "age-years" }, { shared: "resting-hr" }],
    [out("HRR", "bpm", "220 - age - resting_hr", 0)]
  ),
  calc(
    "vo2max-cooper",
    "VO₂max (Cooper 12-min)",
    "fitness-hydration",
    "Cooper test",
    "Aerobic capacity estimate from 12-minute run distance.",
    [{ key: "distance_m", label: "Distance in 12 min (m)", fieldType: "NUMBER", min: 500, max: 3500, defaultValue: 2400 }],
    [out("VO₂max", "mL/kg/min", "(distance_m - 504.9) / 44.73", 1)]
  ),
  calc(
    "sweat-rate",
    "Sweat Rate",
    "fitness-hydration",
    "Fluid loss per hour",
    "Exercise sweat rate from weight change.",
    [{ shared: "weight-kg" }, { key: "sweat_ml", label: "Fluid loss (mL)", fieldType: "NUMBER", min: 0, max: 3000, defaultValue: 800 }, { key: "exercise_h", label: "Exercise duration (hours)", fieldType: "NUMBER", min: 0.25, max: 4, defaultValue: 1 }],
    [out("Sweat rate", "L/h", "sweat_ml / 1000", 2)]
  ),
  calc(
    "fluid-replacement",
    "Exercise Fluid Replacement",
    "fitness-hydration",
    "Post-exercise fluids",
    "Recommended fluid replacement after exercise.",
    [{ shared: "weight-kg" }, { key: "weight_lost_kg", label: "Weight lost (kg)", fieldType: "NUMBER", min: 0, max: 5, defaultValue: 1 }],
    [out("Replace (mL)", "mL", "weight_lost_kg * 1500", 0)]
  ),
  calc(
    "steps-calorie",
    "Calories from Steps",
    "fitness-hydration",
    "Steps to kcal",
    "Approximate calories burned from step count.",
    [{ shared: "weight-kg" }, { key: "steps", label: "Step count", fieldType: "NUMBER", min: 100, max: 50000, defaultValue: 8000 }],
    [out("Calories", "kcal", "steps * weight_kg * 0.00004", 0)]
  ),
  calc(
    "pace-calculator",
    "Running Pace",
    "fitness-hydration",
    "min/km",
    "Pace from distance and time.",
    [{ key: "distance_km", label: "Distance (km)", fieldType: "NUMBER", min: 0.1, max: 100, defaultValue: 5 }, { key: "time_min", label: "Time (minutes)", fieldType: "NUMBER", min: 1, max: 600, defaultValue: 25 }],
    [out("Pace", "min/km", "time_min / (distance_km)", 2)]
  ),
  calc(
    "one-rep-max",
    "One-Rep Max (Epley)",
    "fitness-hydration",
    "Epley formula",
    "Estimated 1RM from submaximal lift.",
    [{ key: "weight_lift", label: "Weight lifted (kg)", fieldType: "NUMBER", min: 1, max: 400, defaultValue: 80 }, { key: "reps", label: "Repetitions", fieldType: "NUMBER", min: 1, max: 15, defaultValue: 5 }],
    [out("1RM", "kg", "weight_lift * (1 + reps / 30)", 1)]
  ),
  calc(
    "calorie-burn-running",
    "Running Calorie Burn",
    "fitness-hydration",
    "MET estimate",
    "Approximate calories burned while running.",
    [{ shared: "weight-kg" }, { key: "met", label: "MET value", fieldType: "NUMBER", min: 3, max: 15, defaultValue: 9 }, { key: "duration_h", label: "Duration (hours)", fieldType: "NUMBER", min: 0.1, max: 5, defaultValue: 0.5 }],
    [out("Calories", "kcal", "met * weight_kg * duration_h", 0)]
  ),
  calc(
    "body-water-percent",
    "Total Body Water",
    "fitness-hydration",
    "Watson formula",
    "Estimated total body water percentage.",
    [{ shared: "age-years" }, { shared: "sex-mf" }, { shared: "height-cm" }, { shared: "weight-kg" }],
    [out("TBW", "L", "sex == 1 ? (2.447 - 0.09156 * age + 0.1074 * height_cm + 0.3362 * weight_kg) : (-2.097 + 0.1069 * height_cm + 0.2466 * weight_kg)", 1)]
  ),
  calc(
    "hydration-urine",
    "Urine Output Rate",
    "fitness-hydration",
    "mL/kg/hr",
    "Urine output normalized to weight and time.",
    [{ shared: "weight-kg" }, { key: "urine_ml", label: "Urine volume (mL)", fieldType: "NUMBER", min: 0, max: 3000, defaultValue: 1200 }, { key: "hours", label: "Hours", fieldType: "NUMBER", min: 1, max: 24, defaultValue: 24 }],
    [out("Urine rate", "mL/kg/h", "urine_ml / weight_kg / hours", 2)]
  ),
  calc(
    "pulse-pressure",
    "Pulse Pressure",
    "cardiology",
    "SBP − DBP",
    "Difference between systolic and diastolic pressure.",
    [{ shared: "systolic-bp" }, { shared: "diastolic-bp" }],
    [out("Pulse Pressure", "mmHg", "sbp - dbp", 0)]
  ),
  calc(
    "map",
    "Mean Arterial Pressure",
    "cardiology",
    "(SBP + 2×DBP)/3",
    "Perfusion pressure estimate.",
    [{ shared: "systolic-bp" }, { shared: "diastolic-bp" }],
    [out("Mean Arterial Pressure", "mmHg", "(sbp + 2 * dbp) / 3", 0)]
  ),
  calc(
    "cardiac-output-fick",
    "Cardiac Output (Fick)",
    "cardiology",
    "CO = VO₂/(Ca−Cv)",
    "Cardiac output from Fick principle.",
    [{ key: "vo2", label: "VO₂ consumption (mL/min)", fieldType: "NUMBER", min: 100, max: 500, defaultValue: 250 }, { key: "ca_o2", label: "Arterial O₂ content (mL/L)", fieldType: "NUMBER", min: 100, max: 250, defaultValue: 200 }, { key: "cv_o2", label: "Mixed venous O₂ (mL/L)", fieldType: "NUMBER", min: 50, max: 200, defaultValue: 150 }],
    [out("Cardiac Output (Fick)", "L/min", "vo2 / (ca_o2 - cv_o2)", 0)]
  ),
  calc(
    "stroke-volume",
    "Stroke Volume",
    "cardiology",
    "SV = CO/HR",
    "Stroke volume from cardiac output and heart rate.",
    [{ key: "co", label: "Cardiac output (L/min)", fieldType: "NUMBER", min: 2, max: 12, defaultValue: 5 }],
    [out("Stroke Volume", "mL", "co / heart_rate", 0)]
  ),
  calc(
    "systemic-vascular-resistance",
    "Systemic Vascular Resistance",
    "cardiology",
    "SVR",
    "Vascular resistance estimate.",
    [{ shared: "systolic-bp" }, { shared: "diastolic-bp" }, { key: "co", label: "Cardiac output (L/min)", fieldType: "NUMBER", min: 2, max: 12, defaultValue: 5 }],
    [out("Systemic Vascular Resistance", "dyn·s/cm⁵", "map * 80 / co", 0)]
  ),
  calc(
    "rate-pressure-product",
    "Rate Pressure Product",
    "cardiology",
    "RPP",
    "Myocardial oxygen demand index.",
    [{ shared: "systolic-bp" }, { shared: "heart-rate" }],
    [out("Rate Pressure Product", "", "sbp * heart_rate", 0)]
  ),
  calc(
    "qt-corrected-bazett",
    "Corrected QT (Bazett)",
    "cardiology",
    "QTc",
    "QT interval corrected for heart rate.",
    [{ key: "qt_ms", label: "QT interval (ms)", fieldType: "NUMBER", min: 200, max: 600, defaultValue: 400 }],
    [out("Corrected QT (Bazett)", "ms", "qt_ms / sqrt(60 / heart_rate)", 0)]
  ),
  calc(
    "shock-index",
    "Shock Index",
    "cardiology",
    "HR/SBP",
    "Triage hemodynamic index.",
    [{ shared: "heart-rate" }, { shared: "systolic-bp" }],
    [out("Shock Index", "", "heart_rate / sbp", 2)]
  ),
  calc(
    "modified-shock-index",
    "Modified Shock Index",
    "cardiology",
    "HR/MAP",
    "Shock index using mean arterial pressure.",
    [{ shared: "heart-rate" }, { shared: "systolic-bp" }, { shared: "diastolic-bp" }],
    [out("Modified Shock Index", "", "heart_rate / ((sbp + 2 * dbp) / 3)", 2)]
  ),
  calc(
    "cardiac-index",
    "Cardiac Index",
    "cardiology",
    "CI = CO/BSA",
    "Cardiac output indexed to body surface area.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }, { key: "co", label: "Cardiac output (L/min)", fieldType: "NUMBER", min: 2, max: 12, defaultValue: 5 }],
    [out("Cardiac Index", "L/min/m²", "co / sqrt(height_cm * weight_kg / 3600)", 2)]
  ),
  calc(
    "creatinine-clearance",
    "Creatinine Clearance (CrCl)",
    "nephrology",
    "Cockcroft-Gault",
    "Estimated creatinine clearance.",
    [{ shared: "age-years" }, { shared: "weight-kg" }, { shared: "sex-mf" }, { shared: "serum-creatinine" }],
    [out("Creatinine Clearance (CrCl)", "mL/min", "((140 - age) * weight_kg / (72 * scr)) * (sex == 0 ? 0.85 : 1)", 2)]
  ),
  calc(
    "egfr-mdrd",
    "eGFR (MDRD simplified)",
    "nephrology",
    "MDRD",
    "Estimated GFR using MDRD equation.",
    [{ shared: "age-years" }, { shared: "sex-mf" }, { shared: "serum-creatinine" }],
    [out("eGFR (MDRD simplified)", "mL/min/1.73m²", "175 * (scr ^ -1.154) * (age ^ -0.203) * (sex == 0 ? 0.742 : 1)", 2)]
  ),
  calc(
    "bun-creatinine-ratio",
    "BUN/Creatinine Ratio",
    "nephrology",
    "BUN/SCr",
    "Prerenal vs intrinsic kidney injury clue.",
    [{ shared: "bun" }, { shared: "serum-creatinine" }],
    [out("BUN/Creatinine Ratio", "", "bun / scr", 2)]
  ),
  calc(
    "fractional-excretion-sodium",
    "Fractional Excretion of Sodium",
    "nephrology",
    "FENa",
    "Differentiates prerenal from ATN.",
    [{ key: "urine_na", label: "Urine sodium (mEq/L)", fieldType: "NUMBER", min: 0, max: 200, defaultValue: 40 }, { key: "urine_cr", label: "Urine creatinine (mg/dL)", fieldType: "NUMBER", min: 1, max: 300, defaultValue: 100 }, { key: "serum_na", label: "Serum sodium (mEq/L)", fieldType: "NUMBER", min: 100, max: 180, defaultValue: 140 }],
    [out("Fractional Excretion of Sodium", "%", "100 * (urine_na * scr) / (serum_na * urine_cr)", 2)]
  ),
  calc(
    "free-water-clearance",
    "Free Water Clearance",
    "nephrology",
    "CH₂O",
    "Free water handling estimate.",
    [{ shared: "urine-osm" }, { shared: "serum-osm" }, { shared: "urine-output-ml" }, { key: "urine_osm", label: "Urine osmolality (mOsm/kg)", fieldType: "NUMBER", min: 50, max: 1200, defaultValue: 500 }, { key: "serum_osm", label: "Serum osmolality (mOsm/kg)", fieldType: "NUMBER", min: 250, max: 350, defaultValue: 290 }],
    [out("Free Water Clearance", "mL/day", "urine_ml * (1 - urine_osm / serum_osm)", 2)]
  ),
  calc(
    "fluid-balance",
    "24h Fluid Balance",
    "nephrology",
    "In − out",
    "Net fluid balance over 24 hours.",
    [{ shared: "fluid-intake-ml" }, { shared: "urine-output-ml" }],
    [out("24h Fluid Balance", "mL", "fluid_ml - urine_ml", 2)]
  ),
  calc(
    "maintenance-fluids-holliday",
    "Maintenance Fluids (Holliday-Segar)",
    "nephrology",
    "4-2-1 rule",
    "Pediatric/adult maintenance fluid estimate.",
    [{ shared: "weight-kg" }],
    [out("Maintenance Fluids (Holliday-Segar)", "mL/day", "weight_kg <= 10 ? weight_kg * 100 : weight_kg <= 20 ? 1000 + (weight_kg - 10) * 50 : 1500 + (weight_kg - 20) * 20", 2)]
  ),
  calc(
    "sodium-deficit",
    "Sodium Deficit",
    "nephrology",
    "Hyponatremia correction",
    "Estimated sodium deficit in hyponatremia.",
    [{ shared: "weight-kg" }, { key: "serum_na", label: "Current sodium (mEq/L)", fieldType: "NUMBER", min: 100, max: 180, defaultValue: 128 }, { key: "target_na", label: "Target sodium (mEq/L)", fieldType: "NUMBER", min: 130, max: 145, defaultValue: 140 }],
    [out("Sodium Deficit", "mEq", "0.6 * weight_kg * (target_na - serum_na)", 2)]
  ),
  calc(
    "corrected-sodium-glucose",
    "Corrected Sodium (Hyperglycemia)",
    "nephrology",
    "Katz correction",
    "Sodium correction for hyperglycemia.",
    [{ shared: "sodium" }, { shared: "glucose" }],
    [out("Corrected Sodium (Hyperglycemia)", "mEq/L", "na + 0.024 * (glucose - 100)", 2)]
  ),
  calc(
    "urine-anion-gap",
    "Urine Anion Gap",
    "nephrology",
    "UAG",
    "Helps classify metabolic acidosis.",
    [{ shared: "urine-na" }, { shared: "urine-k" }, { shared: "urine-cl" }, { key: "urine_na", label: "Urine Na (mEq/L)", fieldType: "NUMBER", min: 0, max: 200, defaultValue: 50 }, { key: "urine_k", label: "Urine K (mEq/L)", fieldType: "NUMBER", min: 0, max: 100, defaultValue: 25 }, { key: "urine_cl", label: "Urine Cl (mEq/L)", fieldType: "NUMBER", min: 0, max: 200, defaultValue: 50 }],
    [out("Urine Anion Gap", "mEq/L", "urine_na + urine_k - urine_cl", 2)]
  ),
  calc(
    "kt-v-dialysis",
    "Kt/V (simplified)",
    "nephrology",
    "Dialysis adequacy",
    "Simplified dialysis adequacy estimate.",
    [{ key: "urea_pre", label: "Pre-dialysis BUN (mg/dL)", fieldType: "NUMBER", min: 10, max: 200, defaultValue: 80 }, { key: "urea_post", label: "Post-dialysis BUN (mg/dL)", fieldType: "NUMBER", min: 5, max: 100, defaultValue: 20 }, { key: "hours", label: "Session hours", fieldType: "NUMBER", min: 2, max: 5, defaultValue: 4 }, { key: "ultrafiltration", label: "Ultrafiltration (L)", fieldType: "NUMBER", min: 0, max: 5, defaultValue: 2 }],
    [out("Kt/V (simplified)", "", "neg_log(urea_post / urea_pre - 0.008 * hours) + (4 - 3.5 * urea_post / urea_pre) * ultrafiltration / weight_kg", 2)]
  ),
  calc(
    "corrected-calcium",
    "Corrected Calcium",
    "clinical-laboratory",
    "Albumin correction",
    "Albumin-adjusted total calcium.",
    [{ shared: "measured-calcium" }, { shared: "albumin" }],
    [out("Corrected Calcium", "mg/dL", "measured_ca + 0.8 * (4 - albumin)", 2)]
  ),
  calc(
    "anion-gap",
    "Anion Gap",
    "clinical-laboratory",
    "Na − (Cl + HCO₃)",
    "Serum anion gap.",
    [{ shared: "sodium" }, { shared: "chloride" }, { shared: "bicarbonate" }],
    [out("Anion Gap", "mEq/L", "na - (cl + hco3)", 2)]
  ),
  calc(
    "albumin-globulin-ratio",
    "Albumin/Globulin Ratio",
    "clinical-laboratory",
    "A/G ratio",
    "Serum protein pattern index.",
    [{ key: "globulin", label: "Globulin (g/dL)", fieldType: "NUMBER", min: 1, max: 6, defaultValue: 2.5 }],
    [out("Albumin/Globulin Ratio", "", "albumin / globulin", 2)]
  ),
  calc(
    "calcium-phosphorus-product",
    "Calcium–Phosphorus Product",
    "clinical-laboratory",
    "Ca × Phos",
    "CKD-MBD risk marker.",
    [{ shared: "measured-calcium" }, { key: "phosphorus", label: "Phosphorus (mg/dL)", fieldType: "NUMBER", min: 1, max: 15, defaultValue: 3.5 }, { key: "ca", label: "Calcium (mg/dL)", fieldType: "NUMBER", min: 4, max: 15, defaultValue: 9 }],
    [out("Calcium–Phosphorus Product", "mg²/dL²", "ca * phosphorus", 2)]
  ),
  calc(
    "osmolality-serum",
    "Calculated Serum Osmolality",
    "clinical-laboratory",
    "2×Na + glucose/18",
    "Estimated serum osmolality.",
    [{ shared: "sodium" }, { shared: "glucose" }, { shared: "bun" }],
    [out("Calculated Serum Osmolality", "mOsm/kg", "2 * na + glucose / 18 + bun / 2.8", 2)]
  ),
  calc(
    "delta-gap",
    "Delta Gap",
    "clinical-laboratory",
    "Δ gap",
    "High anion gap metabolic acidosis helper.",
    [{ shared: "sodium" }, { shared: "chloride" }, { shared: "bicarbonate" }],
    [out("Delta Gap", "mEq/L", "(na - (cl + hco3)) - (12 - hco3)", 2)]
  ),
  calc(
    "transtubular-potassium",
    "Transtubular K Gradient",
    "clinical-laboratory",
    "TTKG",
    "Renal potassium handling.",
    [{ key: "urine_k", label: "Urine K", fieldType: "NUMBER", min: 0, max: 100, defaultValue: 30 }, { key: "serum_k", label: "Serum K", fieldType: "NUMBER", min: 2, max: 8, defaultValue: 4 }, { key: "urine_osm", label: "Urine osmolality", fieldType: "NUMBER", min: 50, max: 1200, defaultValue: 500 }, { key: "serum_osm", label: "Serum osmolality", fieldType: "NUMBER", min: 250, max: 350, defaultValue: 290 }],
    [out("Transtubular K Gradient", "", "(urine_k * serum_osm) / (serum_k * urine_osm)", 2)]
  ),
  calc(
    "rifle-aki",
    "AKI Severity (RIFLE creatinine)",
    "clinical-laboratory",
    "Creatinine-based",
    "Acute kidney injury staging helper.",
    [{ shared: "serum-creatinine" }, { key: "baseline_cr", label: "Baseline creatinine", fieldType: "NUMBER", min: 0.3, max: 10, defaultValue: 1 }],
    [out("AKI Severity (RIFLE creatinine)", "", "baseline_cr > 0 ? scr / baseline_cr : 1", 2)]
  ),
  calc(
    "ldl-friedewald",
    "LDL Cholesterol (Friedewald)",
    "clinical-laboratory",
    "LDL estimate",
    "LDL-C when triglycerides are acceptable.",
    [{ key: "total_chol", label: "Total cholesterol", fieldType: "NUMBER", min: 100, max: 400, defaultValue: 200 }, { key: "hdl", label: "HDL cholesterol", fieldType: "NUMBER", min: 20, max: 120, defaultValue: 55 }, { key: "trig", label: "Triglycerides", fieldType: "NUMBER", min: 50, max: 1000, defaultValue: 150 }],
    [out("LDL Cholesterol (Friedewald)", "mg/dL", "total_chol - hdl - trig / 5", 2)]
  ),
  calc(
    "iron-saturation",
    "Transferrin Saturation",
    "clinical-laboratory",
    "Fe/TIBC",
    "Iron studies index.",
    [{ key: "iron", label: "Serum iron (µg/dL)", fieldType: "NUMBER", min: 10, max: 300, defaultValue: 90 }, { key: "tibc", label: "TIBC (µg/dL)", fieldType: "NUMBER", min: 100, max: 500, defaultValue: 350 }],
    [out("Transferrin Saturation", "%", "100 * iron / tibc", 2)]
  ),
  calc(
    "aa-gradient",
    "Alveolar–Arterial O₂ Gradient",
    "pulmonology",
    "A–a gradient",
    "Oxygenation defect assessment.",
    [{ shared: "fio2-percent" }, { shared: "paco2" }, { shared: "pao2" }],
    [out("Alveolar–Arterial O₂ Gradient", "mmHg", "fio2 * 7.14 - paco2 / 0.8 - pao2", 1)]
  ),
  calc(
    "pf-ratio",
    "P/F Ratio",
    "pulmonology",
    "PaO₂/FiO₂",
    "ARDS severity index.",
    [{ shared: "pao2" }, { shared: "fio2-percent" }],
    [out("P/F Ratio", "mmHg", "pao2 / (fio2 / 100)", 1)]
  ),
  calc(
    "oxygen-content",
    "Arterial Oxygen Content",
    "pulmonology",
    "CaO₂",
    "Oxygen carried in arterial blood.",
    [{ shared: "hb" }, { shared: "pao2" }, { key: "sao2", label: "SaO₂ (%)", fieldType: "NUMBER", min: 70, max: 100, defaultValue: 98 }],
    [out("Arterial Oxygen Content", "mL/dL", "1.34 * hb * sao2 / 100 + 0.003 * pao2", 1)]
  ),
  calc(
    "minute-ventilation",
    "Minute Ventilation",
    "pulmonology",
    "VE",
    "Total ventilation per minute.",
    [{ key: "tidal_volume", label: "Tidal volume (mL)", fieldType: "NUMBER", min: 200, max: 800, defaultValue: 500 }, { key: "respiratory_rate", label: "Respiratory rate", fieldType: "NUMBER", min: 5, max: 40, defaultValue: 16 }],
    [out("Minute Ventilation", "L/min", "tidal_volume * respiratory_rate", 1)]
  ),
  calc(
    "dead-space",
    "Physiologic Dead Space",
    "pulmonology",
    "Bohr equation",
    "Dead space fraction estimate.",
    [{ shared: "paco2" }, { key: "tidal_volume", label: "Tidal volume (mL)", fieldType: "NUMBER", min: 200, max: 800, defaultValue: 500 }, { key: "pe_co2", label: "Mixed expired CO₂", fieldType: "NUMBER", min: 10, max: 60, defaultValue: 35 }],
    [out("Physiologic Dead Space", "mL", "tidal_volume * (paco2 - pe_co2) / paco2", 1)]
  ),
  calc(
    "lung-compliance",
    "Static Lung Compliance",
    "pulmonology",
    "C = V/P",
    "Compliance from volume and pressure.",
    [{ key: "tidal_volume", label: "Tidal volume (mL)", fieldType: "NUMBER", min: 200, max: 800, defaultValue: 450 }, { key: "plateau", label: "Plateau pressure", fieldType: "NUMBER", min: 10, max: 40, defaultValue: 25 }, { key: "peep", label: "PEEP", fieldType: "NUMBER", min: 0, max: 25, defaultValue: 8 }],
    [out("Static Lung Compliance", "mL/cmH₂O", "tidal_volume / (plateau - peep)", 1)]
  ),
  calc(
    "ventilator-tidal-volume",
    "Predicted Tidal Volume",
    "pulmonology",
    "6 mL/kg IBW",
    "Lung-protective tidal volume target.",
    [{ shared: "height-cm" }, { shared: "sex-mf" }, { key: "ibw", label: "IBW (kg)", fieldType: "NUMBER", min: 30, max: 100, defaultValue: 70 }],
    [out("Predicted Tidal Volume", "mL", "6 * ibw", 1)]
  ),
  calc(
    "ibw",
    "Ideal Body Weight (ARDSnet)",
    "pulmonology",
    "ARDSnet IBW",
    "Ideal body weight for ventilation.",
    [{ shared: "height-cm" }, { shared: "sex-mf" }],
    [out("Ideal Body Weight (ARDSnet)", "kg", "sex == 1 ? 50 + 0.91 * (height_cm - 152.4) : 45.5 + 0.91 * (height_cm - 152.4)", 1)]
  ),
  calc(
    "daily-protein-intake",
    "Daily Protein Target",
    "nutrition-diet",
    "g/kg/day",
    "Protein target from body weight.",
    [{ shared: "weight-kg" }, { key: "protein_gkg", label: "Protein (g/kg/day)", fieldType: "NUMBER", min: 0.5, max: 3, defaultValue: 1.2 }],
    [out("Daily Protein Target", "g/day", "protein_gkg * weight_kg", 2)]
  ),
  calc(
    "calorie-deficit",
    "Calorie Deficit for Weight Loss",
    "nutrition-diet",
    "7700 kcal/kg",
    "Daily deficit to lose target kg/week.",
    [{ shared: "weight-kg" }, { key: "weekly_kg", label: "Target loss (kg/week)", fieldType: "NUMBER", min: 0.1, max: 2, defaultValue: 0.5 }],
    [out("Calorie Deficit for Weight Loss", "kcal/day", "7700 * weekly_kg / 7", 2)]
  ),
  calc(
    "macro-carbs",
    "Carbohydrate Calories",
    "nutrition-diet",
    "kcal from carbs",
    "Carb calories from percent of total.",
    [{ key: "total_kcal", label: "Total calories", fieldType: "NUMBER", min: 800, max: 5000, defaultValue: 2000 }, { key: "carb_pct", label: "Carb percent", fieldType: "NUMBER", min: 10, max: 70, defaultValue: 45 }],
    [out("Carbohydrate Calories", "kcal", "total_kcal * carb_pct / 100", 2)]
  ),
  calc(
    "macro-fat",
    "Fat Calories",
    "nutrition-diet",
    "kcal from fat",
    "Fat calories from percent of total.",
    [{ key: "total_kcal", label: "Total calories", fieldType: "NUMBER", min: 800, max: 5000, defaultValue: 2000 }, { key: "fat_pct", label: "Fat percent", fieldType: "NUMBER", min: 10, max: 70, defaultValue: 30 }],
    [out("Fat Calories", "kcal", "total_kcal * fat_pct / 100", 2)]
  ),
  calc(
    "macro-protein",
    "Protein Calories",
    "nutrition-diet",
    "kcal from protein",
    "Protein calories from grams.",
    [{ key: "protein_g", label: "Protein (grams)", fieldType: "NUMBER", min: 20, max: 400, defaultValue: 100 }],
    [out("Protein Calories", "kcal", "protein_g * 4", 2)]
  ),
  calc(
    "fiber-intake",
    "Fiber Recommendation",
    "nutrition-diet",
    "14 g/1000 kcal",
    "Dietary fiber target.",
    [{ key: "total_kcal", label: "Total calories", fieldType: "NUMBER", min: 800, max: 5000, defaultValue: 2000 }],
    [out("Fiber Recommendation", "g/day", "14 * (total_kcal / 1000)", 2)]
  ),
  calc(
    "alcohol-units",
    "Alcohol Units",
    "nutrition-diet",
    "Standard drinks",
    "Convert ethanol grams to units.",
    [{ key: "ethanol_g", label: "Ethanol (grams)", fieldType: "NUMBER", min: 0, max: 200, defaultValue: 14 }],
    [out("Alcohol Units", "units", "ethanol_g / 10", 2)]
  ),
  calc(
    "glycemic-index-load",
    "Glycemic Load",
    "nutrition-diet",
    "GL",
    "Glycemic load from GI and carbs.",
    [{ key: "gi", label: "Glycemic index", fieldType: "NUMBER", min: 0, max: 100, defaultValue: 55 }, { key: "carbs_g", label: "Carbohydrate (g)", fieldType: "NUMBER", min: 0, max: 200, defaultValue: 50 }],
    [out("Glycemic Load", "", "gi * carbs_g / 100", 2)]
  ),
  calc(
    "meal-calories",
    "Calories per Meal",
    "nutrition-diet",
    "Split meals",
    "Calories per meal from daily total.",
    [{ key: "daily_kcal", label: "Daily calories", fieldType: "NUMBER", min: 800, max: 5000, defaultValue: 2000 }, { key: "meals", label: "Meals per day", fieldType: "NUMBER", min: 1, max: 8, defaultValue: 3 }],
    [out("Calories per Meal", "kcal", "daily_kcal / meals", 2)]
  ),
  calc(
    "sodium-intake",
    "Sodium Intake",
    "nutrition-diet",
    "mg/day",
    "Sodium from salt grams.",
    [{ key: "salt_g", label: "Salt (grams)", fieldType: "NUMBER", min: 0, max: 20, defaultValue: 6 }],
    [out("Sodium Intake", "mg", "salt_g * 393", 2)]
  ),
  calc(
    "water-from-weight",
    "Hydration from Weight",
    "nutrition-diet",
    "30–35 mL/kg",
    "Alternative hydration estimate.",
    [{ shared: "weight-kg" }],
    [out("Hydration from Weight", "mL/day", "weight_kg * 33", 2)]
  ),
  calc(
    "calorie-surplus",
    "Calorie Surplus",
    "nutrition-diet",
    "Lean gain",
    "Surplus for muscle gain goal.",
    [{ key: "tdee", label: "Maintenance calories", fieldType: "NUMBER", min: 1200, max: 5000, defaultValue: 2200 }, { key: "surplus", label: "Daily surplus", fieldType: "NUMBER", min: 100, max: 1000, defaultValue: 300 }],
    [out("Calorie Surplus", "kcal/day", "tdee + surplus", 2)]
  ),
  calc(
    "protein-per-meal",
    "Protein per Meal",
    "nutrition-diet",
    "g/meal",
    "Distribute protein across meals.",
    [{ key: "daily_protein", label: "Daily protein (g)", fieldType: "NUMBER", min: 40, max: 300, defaultValue: 120 }, { key: "meals", label: "Meals", fieldType: "NUMBER", min: 1, max: 8, defaultValue: 3 }],
    [out("Protein per Meal", "g", "daily_protein / meals", 2)]
  ),
  calc(
    "carb-to-insulin",
    "Carbohydrate to Insulin Ratio",
    "nutrition-diet",
    "g/unit",
    "Insulin dosing education aid (not medical advice).",
    [{ key: "carb_g", label: "Carbs (g)", fieldType: "NUMBER", min: 0, max: 200, defaultValue: 45 }, { key: "insulin_units", label: "Insulin units", fieldType: "NUMBER", min: 0.5, max: 30, defaultValue: 4 }],
    [out("Carbohydrate to Insulin Ratio", "g/unit", "carb_g / insulin_units", 2)]
  ),
  calc(
    "energy-availability",
    "Energy Availability",
    "nutrition-diet",
    "kcal/kg FFM",
    "Relative energy availability in athletes.",
    [{ shared: "weight-kg" }, { key: "energy_intake", label: "Energy intake (kcal)", fieldType: "NUMBER", min: 1000, max: 6000, defaultValue: 2500 }, { key: "ffm", label: "Fat-free mass (kg)", fieldType: "NUMBER", min: 30, max: 100, defaultValue: 55 }],
    [out("Energy Availability", "kcal/kg", "energy_intake / ffm", 2)]
  ),
  calc(
    "meld-score",
    "MELD Score (simplified)",
    "gastroenterology",
    "MELD",
    "Liver disease severity score (simplified inputs).",
    [{ shared: "serum-creatinine" }, { shared: "bilirubin" }, { shared: "inr" }],
    [out("MELD Score", "points", "3.78 * log(bilirubin) + 11.2 * log(inr) + 9.57 * log(scr) + 6.43", 2)]
  ),
  calc(
    "child-pugh",
    "Child-Pugh Points",
    "gastroenterology",
    "Child-Pugh",
    "Cirrhosis severity classification points.",
    [],
    [out("Child-Pugh Points", "points", "bilirubin_pts + albumin_pts + inr_pts + ascites_pts + enceph_pts", 2)]
  ),
  calc(
    "ast-alt-ratio",
    "AST/ALT Ratio",
    "gastroenterology",
    "De Ritis",
    "Hepatocellular injury pattern.",
    [{ shared: "ast" }, { shared: "alt" }],
    [out("AST/ALT Ratio", "", "ast / alt", 2)]
  ),
  calc(
    "fib4",
    "FIB-4 Index",
    "gastroenterology",
    "Fibrosis screening",
    "Liver fibrosis screening index.",
    [{ shared: "age-years" }, { shared: "ast" }, { shared: "alt" }, { shared: "platelet-count" }],
    [out("FIB-4 Index", "", "(age * ast) / (plt * sqrt(alt))", 2)]
  ),
  calc(
    "albumin-corrected-anion",
    "Albumin-corrected Anion Gap",
    "gastroenterology",
    "Corrected AG",
    "Anion gap adjusted for albumin.",
    [{ shared: "sodium" }, { shared: "chloride" }, { shared: "bicarbonate" }, { shared: "albumin" }],
    [out("Albumin-corrected Anion Gap", "mEq/L", "na - (cl + hco3) + 2.5 * (4 - albumin)", 2)]
  ),
  calc(
    "hepatic-encephalopathy-grade",
    "HE Grade Helper",
    "gastroenterology",
    "West Haven",
    "Maps ammonia to suggested grade (educational).",
    [{ key: "ammonia", label: "Ammonia (µmol/L)", fieldType: "NUMBER", min: 10, max: 300, defaultValue: 45 }],
    [out("HE Grade Helper", "", "ammonia > 100 ? 2 : ammonia > 75 ? 1 : 0", 2)]
  ),
  calc(
    "na-maddens",
    "Maddrey Discriminant Function",
    "gastroenterology",
    "DF",
    "Alcoholic hepatitis severity.",
    [{ shared: "bilirubin" }],
    [out("Maddrey Discriminant Function", "", "4.6 * (bilirubin - 1.0)", 2)]
  ),
  calc(
    "forrest-risk",
    "Upper GI Bleeding Risk",
    "gastroenterology",
    "Blatchford proxy",
    "Simplified bleeding risk placeholder.",
    [{ shared: "hb" }, { shared: "sbp" }, { shared: "heart-rate" }],
    [out("Upper GI Bleeding Risk", "", "blatchford_proxy", 2)]
  ),
  calc(
    "glasgow-blatchford",
    "Glasgow-Blatchford Score",
    "gastroenterology",
    "GBS",
    "UGIB risk stratification (simplified).",
    [{ shared: "hb" }, { shared: "sbp" }, { shared: "heart-rate" }],
    [out("Glasgow-Blatchford Score", "points", "gbs_points", 2)]
  ),
  calc(
    "ranson-score",
    "Ranson Criteria Points",
    "gastroenterology",
    "Ranson",
    "Acute pancreatitis severity (simplified).",
    [],
    [out("Ranson Criteria Points", "points", "ranson_points", 2)]
  ),
  calc(
    "anc",
    "Absolute Neutrophil Count",
    "hematology",
    "ANC",
    "Neutrophil count from WBC and percent.",
    [{ shared: "wbc" }, { shared: "neut_pct" }, { key: "neut_pct", label: "Neutrophil %", fieldType: "NUMBER", min: 0, max: 100, defaultValue: 60 }],
    [out("Absolute Neutrophil Count", "/µL", "wbc * 1000 * neut_pct / 100", 2)]
  ),
  calc(
    "corrected-wbc",
    "Corrected WBC for Nucleated RBC",
    "hematology",
    "Corrected WBC",
    "Corrects for nucleated red cells.",
    [{ shared: "wbc" }, { shared: "nRBC" }, { key: "nRBC", label: "nRBC per 100 WBC", fieldType: "NUMBER", min: 0, max: 50, defaultValue: 0 }],
    [out("Corrected WBC for Nucleated RBC", "/µL", "wbc * 1000 / (1 + nRBC)", 2)]
  ),
  calc(
    "mentzer-index",
    "Mentzer Index",
    "hematology",
    "MCV/RBC",
    "Thalassemia vs iron deficiency clue.",
    [{ key: "mcv", label: "MCV (fL)", fieldType: "NUMBER", min: 60, max: 120, defaultValue: 85 }, { key: "rbc_millions", label: "RBC (millions/µL)", fieldType: "NUMBER", min: 2, max: 8, defaultValue: 4.5 }],
    [out("Mentzer Index", "", "mcv / rbc_millions", 2)]
  ),
  calc(
    "rdw-cv-helper",
    "RDW Interpretation",
    "hematology",
    "RDW flag",
    "Flags likely variation pattern.",
    [{ shared: "rdw" }, { key: "rdw", label: "RDW (%)", fieldType: "NUMBER", min: 10, max: 25, defaultValue: 13 }],
    [out("RDW Interpretation", "", "rdw > 15 ? 1 : 0", 2)]
  ),
  calc(
    "inr-therapeutic",
    "INR Therapeutic Range",
    "hematology",
    "Warfarin",
    "Distance from therapeutic INR.",
    [{ shared: "inr" }, { key: "target_inr", label: "Target INR", fieldType: "NUMBER", min: 1.5, max: 4, defaultValue: 2.5 }],
    [out("INR Therapeutic Range", "", "abs(inr - target_inr)", 2)]
  ),
  calc(
    "bleeding-risk-platelets",
    "Platelet Transfusion Threshold",
    "hematology",
    "Threshold",
    "Educational threshold comparison.",
    [{ shared: "plt" }, { key: "threshold", label: "Threshold (×10³/µL)", fieldType: "NUMBER", min: 10, max: 100, defaultValue: 50 }],
    [out("Platelet Transfusion Threshold", "", "plt < threshold ? 1 : 0", 2)]
  ),
  calc(
    "iron-deficiency-index",
    "Transferrin Saturation Index",
    "hematology",
    "TSAT",
    "Iron deficiency screening.",
    [],
    [out("Transferrin Saturation Index", "%", "100 * iron / tibc", 2)]
  ),
  calc(
    "reticulocyte-index",
    "Reticulocyte Production Index",
    "hematology",
    "RPI",
    "Marrow response to anemia.",
    [{ key: "retic_pct", label: "Reticulocyte %", fieldType: "NUMBER", min: 0, max: 30, defaultValue: 1.5 }, { key: "hct", label: "Hematocrit %", fieldType: "NUMBER", min: 15, max: 60, defaultValue: 36 }, { key: "maturation", label: "Maturation factor", fieldType: "NUMBER", min: 1, max: 3, defaultValue: 2 }],
    [out("Reticulocyte Production Index", "", "retic_pct * hct / 45 * (1 / maturation)", 2)]
  ),
  calc(
    "fibrinogen-level",
    "Fibrinogen Convert",
    "hematology",
    "mg/dL to g/L",
    "Unit conversion for fibrinogen.",
    [{ key: "fibrinogen_mgdl", label: "Fibrinogen (mg/dL)", fieldType: "NUMBER", min: 50, max: 800, defaultValue: 300 }],
    [out("Fibrinogen Convert", "g/L", "fibrinogen_mgdl / 100", 2)]
  ),
  calc(
    "mean-corpuscular-hb",
    "MCH",
    "hematology",
    "Hb/RBC",
    "Mean corpuscular hemoglobin.",
    [{ shared: "hb" }, { shared: "rbc_millions" }, { key: "rbc_millions", label: "RBC (millions/µL)", fieldType: "NUMBER", min: 2, max: 8, defaultValue: 4.5 }],
    [out("MCH", "pg", "hb / rbc_millions", 2)]
  ),
  calc(
    "homa-ir",
    "HOMA-IR",
    "endocrinology",
    "Insulin resistance",
    "Homeostatic model assessment.",
    [{ key: "insulin", label: "Fasting insulin (µIU/mL)", fieldType: "NUMBER", min: 1, max: 100, defaultValue: 10 }],
    [out("HOMA-IR", "", "glucose * insulin / 405", 2)]
  ),
  calc(
    "quicki",
    "QUICKI",
    "endocrinology",
    "Insulin sensitivity",
    "Quantitative insulin sensitivity check.",
    [],
    [out("QUICKI", "", "1 / (log(glucose) + log(insulin))", 2)]
  ),
  calc(
    "a1c-eag",
    "eAG from HbA1c",
    "endocrinology",
    "ADAG",
    "Estimated average glucose from A1c.",
    [{ key: "a1c", label: "HbA1c (%)", fieldType: "NUMBER", min: 4, max: 15, defaultValue: 7 }],
    [out("eAG from HbA1c", "mg/dL", "28.7 * a1c - 46.7", 2)]
  ),
  calc(
    "corrected-sodium",
    "Corrected Sodium",
    "endocrinology",
    "Hyperglycemia",
    "Sodium correction for glucose.",
    [{ shared: "sodium" }, { shared: "glucose" }],
    [out("Corrected Sodium", "mEq/L", "na + 0.024 * (glucose - 100)", 2)]
  ),
  calc(
    "free-testosterone",
    "Free Testosterone Index",
    "endocrinology",
    "FTI",
    "Calculated free testosterone index.",
    [{ key: "total_t", label: "Total testosterone", fieldType: "NUMBER", min: 50, max: 1500, defaultValue: 400 }, { key: "shbg_ratio", label: "SHBG ratio factor", fieldType: "NUMBER", min: 0.1, max: 2, defaultValue: 1 }],
    [out("Free Testosterone Index", "ng/dL", "total_t * shbg_ratio", 2)]
  ),
  calc(
    "tsh-t4-ratio",
    "TSH/T4 Ratio",
    "endocrinology",
    "Thyroid balance",
    "Thyroid function pattern index.",
    [{ key: "tsh", label: "TSH (mIU/L)", fieldType: "NUMBER", min: 0.01, max: 50, defaultValue: 2 }, { key: "free_t4", label: "Free T4 (ng/dL)", fieldType: "NUMBER", min: 0.1, max: 5, defaultValue: 1.2 }],
    [out("TSH/T4 Ratio", "", "tsh / free_t4", 2)]
  ),
  calc(
    "calcium-phos-product",
    "Ca×Phos Product",
    "endocrinology",
    "CKD-MBD",
    "Mineral bone disorder marker.",
    [{ shared: "measured-calcium" }, { key: "ca", label: "Calcium", fieldType: "NUMBER", min: 4, max: 15, defaultValue: 9 }, { key: "phos", label: "Phosphorus", fieldType: "NUMBER", min: 1, max: 15, defaultValue: 3.5 }],
    [out("Ca×Phos Product", "mg²/dL²", "ca * phos", 2)]
  ),
  calc(
    "insulin-dose-weight",
    "Weight-Based Insulin",
    "endocrinology",
    "0.5–1 U/kg",
    "Educational total daily insulin estimate.",
    [{ shared: "weight-kg" }, { key: "units_per_kg", label: "Units/kg/day", fieldType: "NUMBER", min: 0.2, max: 2, defaultValue: 0.6 }],
    [out("Weight-Based Insulin", "units/day", "units_per_kg * weight_kg", 2)]
  ),
  calc(
    "steroid-conversion",
    "Steroid Dose Conversion",
    "endocrinology",
    "Prednisone equiv",
    "Glucocorticoid equivalence.",
    [{ key: "dose_mg", label: "Dose (mg)", fieldType: "NUMBER", min: 0.5, max: 100, defaultValue: 5 }, { key: "factor", label: "Equivalence factor", fieldType: "NUMBER", min: 0.1, max: 10, defaultValue: 1 }],
    [out("Steroid Dose Conversion", "mg prednisone equiv", "dose_mg * factor", 2)]
  ),
  calc(
    "bmr-diabetes",
    "Adjusted BMR Diabetes",
    "endocrinology",
    "Activity",
    "BMR with diabetes activity factor.",
    [{ shared: "age-years" }, { shared: "sex-mf" }, { shared: "height-cm" }, { shared: "weight-kg" }, { key: "diabetes_factor", label: "Activity factor", fieldType: "NUMBER", min: 1, max: 1.8, defaultValue: 1.2 }],
    [out("Adjusted BMR Diabetes", "kcal", "(10 * weight_kg + 6.25 * height_cm - 5 * age + (sex == 1 ? 5 : -161)) * diabetes_factor", 2)]
  ),
  calc(
    "anion-gap-osm",
    "Osmolar Gap",
    "endocrinology",
    "Toxic alcohol screen",
    "Gap between measured and calculated osmolality.",
    [{ key: "measured_osm", label: "Measured osm", fieldType: "NUMBER", min: 250, max: 400, defaultValue: 290 }, { key: "calculated_osm", label: "Calculated osm", fieldType: "NUMBER", min: 250, max: 400, defaultValue: 290 }],
    [out("Osmolar Gap", "mOsm", "measured_osm - calculated_osm", 2)]
  ),
  calc(
    "qsofa",
    "qSOFA Score",
    "emergency-critical-care",
    "qSOFA",
    "Quick SOFA for sepsis screening.",
    [{ shared: "sbp" }, { shared: "respiratory-rate" }, { shared: "gcs" }, { key: "gcs", label: "GCS", fieldType: "NUMBER", min: 3, max: 15, defaultValue: 15 }, { key: "respiratory-rate", label: "Respiratory rate", fieldType: "NUMBER", min: 4, max: 60, defaultValue: 18 }],
    [out("qSOFA Score", "points", "qsofa_points", 2)]
  ),
  calc(
    "news2",
    "NEWS2 (simplified)",
    "emergency-critical-care",
    "NEWS2",
    "National Early Warning Score (simplified).",
    [{ shared: "respiratory-rate" }, { shared: "sbp" }, { shared: "heart-rate" }, { shared: "body-temperature" }],
    [out("NEWS2", "points", "news2_points", 2)]
  ),
  calc(
    "apache-proxy",
    "Severity Proxy Score",
    "emergency-critical-care",
    "ICU proxy",
    "Educational severity proxy from vitals.",
    [{ shared: "sbp" }, { shared: "heart-rate" }, { shared: "age-years" }],
    [out("Severity Proxy Score", "points", "apache_proxy", 2)]
  ),
  calc(
    "parkland-burns",
    "Parkland Formula",
    "emergency-critical-care",
    "Burn resuscitation",
    "24h fluid for burns.",
    [{ shared: "weight-kg" }, { key: "tbsa", label: "TBSA burn %", fieldType: "NUMBER", min: 1, max: 100, defaultValue: 20 }],
    [out("Parkland Formula", "mL", "4 * weight_kg * tbsa", 2)]
  ),
  calc(
    "gcs-total",
    "Glasgow Coma Scale",
    "emergency-critical-care",
    "GCS",
    "Sum of eye, verbal, motor.",
    [{ key: "eye", label: "Eye (1-4)", fieldType: "NUMBER", min: 1, max: 4, defaultValue: 4 }, { key: "verbal", label: "Verbal (1-5)", fieldType: "NUMBER", min: 1, max: 5, defaultValue: 5 }, { key: "motor", label: "Motor (1-6)", fieldType: "NUMBER", min: 1, max: 6, defaultValue: 6 }],
    [out("Glasgow Coma Scale", "points", "eye + verbal + motor", 2)]
  ),
  calc(
    "wells-pe",
    "Wells PE Score",
    "emergency-critical-care",
    "Wells",
    "Pulmonary embolism pretest probability (simplified).",
    [],
    [out("Wells PE Score", "points", "wells_pe_points", 2)]
  ),
  calc(
    "perc-rule",
    "PERC Rule",
    "emergency-critical-care",
    "PERC",
    "Pulmonary embolism rule-out (simplified).",
    [{ shared: "age-years" }, { shared: "heart-rate" }, { shared: "sbp" }],
    [out("PERC Rule", "", "perc_positive", 2)]
  ),
  calc(
    "curb65",
    "CURB-65",
    "emergency-critical-care",
    "CURB-65",
    "Pneumonia severity (simplified).",
    [{ shared: "age-years" }],
    [out("CURB-65", "points", "curb65_points", 2)]
  ),
  calc(
    "psi-port",
    "Pneumonia Severity Index",
    "emergency-critical-care",
    "PSI proxy",
    "Community pneumonia risk proxy.",
    [{ shared: "age-years" }],
    [out("Pneumonia Severity Index", "points", "psi_proxy", 2)]
  ),
  calc(
    "sofa-proxy",
    "SOFA Proxy",
    "emergency-critical-care",
    "SOFA",
    "Organ dysfunction proxy score.",
    [{ shared: "sbp" }, { shared: "platelet-count" }, { shared: "serum-creatinine" }, { shared: "bilirubin" }],
    [out("SOFA Proxy", "points", "sofa_proxy", 2)]
  ),
  calc(
    "anion-gap-lactate",
    "Lactate Clearance",
    "emergency-critical-care",
    "Clearance %",
    "Percent lactate clearance.",
    [{ key: "initial_lac", label: "Initial lactate", fieldType: "NUMBER", min: 0.5, max: 20, defaultValue: 4 }, { key: "current_lac", label: "Current lactate", fieldType: "NUMBER", min: 0.1, max: 20, defaultValue: 2 }],
    [out("Lactate Clearance", "%", "100 * (initial_lac - current_lac) / initial_lac", 2)]
  ),
  calc(
    "dose-epinephrine",
    "Epinephrine Dose",
    "emergency-critical-care",
    "mcg/min",
    "Infusion dose from concentration.",
    [{ key: "mcg_kg_min", label: "mcg/kg/min", fieldType: "NUMBER", min: 0.01, max: 2, defaultValue: 0.1 }],
    [out("Epinephrine Dose", "mcg/min", "mcg_kg_min * weight_kg", 2)]
  ),
  calc(
    "weight-based-dose",
    "Weight-Based Dose",
    "pharmacology",
    "mg/kg",
    "Total dose from mg/kg.",
    [{ shared: "weight-kg" }, { key: "mg_per_kg", label: "Dose (mg/kg)", fieldType: "NUMBER", min: 0.01, max: 50, defaultValue: 10 }],
    [out("Weight-Based Dose", "mg", "mg_per_kg * weight_kg", 2)]
  ),
  calc(
    "iv-drip-rate",
    "IV Drip Rate",
    "pharmacology",
    "mL/hr",
    "Infusion rate from dose and concentration.",
    [{ key: "dose_mcg_kg_min", label: "mcg/kg/min", fieldType: "NUMBER", min: 0.01, max: 20, defaultValue: 5 }, { key: "concentration", label: "Concentration (mcg/mL)", fieldType: "NUMBER", min: 1, max: 1600, defaultValue: 400 }],
    [out("IV Drip Rate", "mL/hr", "dose_mcg_kg_min * weight_kg * 60 / concentration", 2)]
  ),
  calc(
    "pediatric-dose-young",
    "Pediatric Dose (Young's)",
    "pharmacology",
    "Age-based",
    "Clark/Young rule dose fraction.",
    [{ shared: "age-years" }, { key: "adult_dose", label: "Adult dose (mg)", fieldType: "NUMBER", min: 1, max: 2000, defaultValue: 500 }],
    [out("Pediatric Dose", "mg", "adult_dose * age / (age + 12)", 2)]
  ),
  calc(
    "bsa-dose",
    "BSA-Based Dose",
    "pharmacology",
    "mg/m²",
    "Chemotherapy BSA dosing.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }, { key: "dose_per_m2", label: "Dose (mg/m²)", fieldType: "NUMBER", min: 1, max: 500, defaultValue: 75 }],
    [out("BSA-Based Dose", "mg", "dose_per_m2 * sqrt(height_cm * weight_kg / 3600)", 2)]
  ),
  calc(
    "opioid-mme",
    "Morphine Milligram Equivalents",
    "pharmacology",
    "MME",
    "Opioid equivalence calculator.",
    [{ key: "morphine_mg", label: "Morphine (mg/day)", fieldType: "NUMBER", min: 0, max: 500, defaultValue: 30 }, { key: "oxycodone_mg", label: "Oxycodone (mg/day)", fieldType: "NUMBER", min: 0, max: 500, defaultValue: 0 }, { key: "hydromorphone_mg", label: "Hydromorphone (mg/day)", fieldType: "NUMBER", min: 0, max: 200, defaultValue: 0 }],
    [out("Morphine Milligram Equivalents", "MME/day", "morphine_mg * 1 + oxycodone_mg * 1.5 + hydromorphone_mg * 5", 2)]
  ),
  calc(
    "paracetamol-toxicity",
    "Paracetamol Toxicity Risk",
    "pharmacology",
    "Nomogram proxy",
    "Risk flag vs dose (educational).",
    [{ key: "dose_g", label: "Single dose (grams)", fieldType: "NUMBER", min: 0, max: 50, defaultValue: 4 }],
    [out("Paracetamol Toxicity Risk", "", "dose_g > 7.5 ? 1 : 0", 2)]
  ),
  calc(
    "antibiotic-renal",
    "Renal Dose Adjustment",
    "pharmacology",
    "CrCl factor",
    "Dose reduction factor from CrCl.",
    [{ shared: "age-years" }, { shared: "weight-kg" }, { shared: "sex-mf" }, { shared: "serum-creatinine" }],
    [out("Renal Dose Adjustment", "", "crcl_factor", 2)]
  ),
  calc(
    "drip-factor",
    "Drop Factor Rate",
    "pharmacology",
    "gtt/min",
    "IV drip rate from mL/hr.",
    [{ key: "ml_per_hr", label: "mL/hr", fieldType: "NUMBER", min: 1, max: 1000, defaultValue: 100 }, { key: "drop_factor", label: "Drop factor", fieldType: "NUMBER", min: 10, max: 60, defaultValue: 20 }],
    [out("Drop Factor Rate", "gtt/min", "ml_per_hr * drop_factor / 60", 2)]
  ),
  calc(
    "concentration-dilution",
    "Solution Dilution",
    "pharmacology",
    "C1V1=C2V2",
    "Stock dilution calculator.",
    [{ key: "c1", label: "Stock concentration", fieldType: "NUMBER", min: 0.1, max: 100, defaultValue: 10 }, { key: "v1", label: "Volume stock (mL)", fieldType: "NUMBER", min: 0.1, max: 1000, defaultValue: 10 }, { key: "c2", label: "Final concentration", fieldType: "NUMBER", min: 0.01, max: 50, defaultValue: 1 }],
    [out("Solution Dilution", "mL", "c1 * v1 / c2", 2)]
  ),
  calc(
    "mg-ml-conversion",
    "mg to mL",
    "pharmacology",
    "Liquid dose",
    "Convert mg dose to volume.",
    [{ key: "dose_mg", label: "Dose (mg)", fieldType: "NUMBER", min: 0.1, max: 5000, defaultValue: 250 }, { key: "conc_mg_ml", label: "Concentration (mg/mL)", fieldType: "NUMBER", min: 0.01, max: 500, defaultValue: 25 }],
    [out("mg to mL", "mL", "dose_mg / conc_mg_ml", 2)]
  ),
  calc(
    "pediatric-fluid",
    "Pediatric Maintenance Fluids",
    "pharmacology",
    "Holliday-Segar",
    "Maintenance fluids by weight.",
    [{ shared: "weight-kg" }],
    [out("Pediatric Maintenance Fluids", "mL/day", "weight_kg <= 10 ? weight_kg * 100 : weight_kg <= 20 ? 1000 + (weight_kg - 10) * 50 : 1500 + (weight_kg - 20) * 20", 2)]
  ),
  calc(
    "heparin-weight",
    "Heparin Loading Dose",
    "pharmacology",
    "Units/kg",
    "Weight-based heparin bolus.",
    [{ shared: "weight-kg" }, { key: "units_per_kg", label: "Units/kg", fieldType: "NUMBER", min: 10, max: 120, defaultValue: 80 }],
    [out("Heparin Loading Dose", "units", "units_per_kg * weight_kg", 2)]
  ),
  calc(
    "vancomycin-dose",
    "Vancomycin Dose",
    "pharmacology",
    "mg/kg",
    "Initial vancomycin dose estimate.",
    [{ shared: "weight-kg" }],
    [out("Vancomycin Dose", "mg", "15 * weight_kg", 2)]
  ),
  calc(
    "gentamicin-dose",
    "Gentamicin Dose",
    "pharmacology",
    "mg/kg",
    "Aminoglycoside weight-based dose.",
    [{ shared: "weight-kg" }, { key: "dose_mg_kg", label: "mg/kg", fieldType: "NUMBER", min: 1, max: 10, defaultValue: 5 }],
    [out("Gentamicin Dose", "mg", "dose_mg_kg * weight_kg", 2)]
  ),
  calc(
    "edd-lmp",
    "Estimated Due Date",
    "obstetrics-pediatrics",
    "Naegele",
    "EDD from LMP (simplified).",
    [{ key: "lmp_day", label: "Days since LMP", fieldType: "NUMBER", min: 0, max: 300, defaultValue: 60 }],
    [out("Estimated Due Date", "days from LMP", "lmp_day + 280", 2)]
  ),
  calc(
    "gestational-age",
    "Gestational Age",
    "obstetrics-pediatrics",
    "Weeks",
    "Gestational age from days.",
    [{ key: "days", label: "Days since LMP", fieldType: "NUMBER", min: 0, max: 320, defaultValue: 196 }],
    [out("Gestational Age", "weeks", "days / 7", 2)]
  ),
  calc(
    "fetal-weight-hadlock",
    "Estimated Fetal Weight",
    "obstetrics-pediatrics",
    "Hadlock proxy",
    "Ultrasound EFW proxy.",
    [{ key: "efw_g", label: "EFW (grams)", fieldType: "NUMBER", min: 200, max: 6000, defaultValue: 3200 }],
    [out("Estimated Fetal Weight", "kg", "efw_g / 1000", 2)]
  ),
  calc(
    "apgar",
    "Apgar Score",
    "obstetrics-pediatrics",
    "Apgar",
    "Neonatal Apgar sum.",
    [{ key: "appearance", label: "Appearance (0-2)", fieldType: "NUMBER", min: 0, max: 2, defaultValue: 2 }, { key: "pulse", label: "Pulse (0-2)", fieldType: "NUMBER", min: 0, max: 2, defaultValue: 2 }, { key: "grimace", label: "Grimace (0-2)", fieldType: "NUMBER", min: 0, max: 2, defaultValue: 2 }, { key: "activity", label: "Activity (0-2)", fieldType: "NUMBER", min: 0, max: 2, defaultValue: 2 }, { key: "resp", label: "Respiration (0-2)", fieldType: "NUMBER", min: 0, max: 2, defaultValue: 2 }],
    [out("Apgar Score", "points", "appearance + pulse + grimace + activity + resp", 2)]
  ),
  calc(
    "pediatric-bmi",
    "Pediatric BMI",
    "obstetrics-pediatrics",
    "BMI",
    "BMI for children (value only).",
    [{ shared: "height-cm" }, { shared: "weight-kg" }],
    [out("Pediatric BMI", "kg/m²", "weight_kg / (height_cm / 100) ^ 2", 2)]
  ),
  calc(
    "ibw-pediatric",
    "Pediatric IBW",
    "obstetrics-pediatrics",
    "IBW",
    "Ideal body weight pediatric formula.",
    [{ shared: "height-cm" }, { shared: "sex-mf" }],
    [out("Pediatric IBW", "kg", "sex == 1 ? 50 + 0.91 * (height_cm - 152.4) : 45.5 + 0.91 * (height_cm - 152.4)", 2)]
  ),
  calc(
    "neonatal-glucose",
    "Neonatal Glucose",
    "obstetrics-pediatrics",
    "mg/dL",
    "Screening value entry.",
    [{ shared: "glucose" }],
    [out("Neonatal Glucose", "mg/dL", "glucose", 2)]
  ),
  calc(
    "fluid-neonate",
    "Neonate Fluid",
    "obstetrics-pediatrics",
    "mL/kg/day",
    "Neonatal maintenance fluids.",
    [{ shared: "weight-kg" }, { key: "ml_kg_day", label: "mL/kg/day", fieldType: "NUMBER", min: 60, max: 200, defaultValue: 100 }],
    [out("Neonate Fluid", "mL/day", "weight_kg * ml_kg_day", 2)]
  ),
  calc(
    "downes-score",
    "Downes Score",
    "obstetrics-pediatrics",
    "Resp distress",
    "Neonatal respiratory distress (simplified).",
    [],
    [out("Downes Score", "points", "downes_points", 2)]
  ),
  calc(
    "pews",
    "PEWS",
    "obstetrics-pediatrics",
    "Pediatric early warning",
    "Pediatric early warning proxy.",
    [{ shared: "heart-rate" }, { shared: "sbp" }, { shared: "respiratory-rate" }],
    [out("PEWS", "points", "pews_points", 2)]
  ),
  calc(
    "target-height-midparent",
    "Mid-Parental Height",
    "obstetrics-pediatrics",
    "Target height",
    "Predicted adult height.",
    [{ key: "mother", label: "Mother height (cm)", fieldType: "NUMBER", min: 140, max: 200, defaultValue: 165 }, { key: "father", label: "Father height (cm)", fieldType: "NUMBER", min: 150, max: 210, defaultValue: 178 }],
    [out("Mid-Parental Height", "cm", "(mother + father) / 2 + (sex == 1 ? 13 : -13)", 2)]
  ),
  calc(
    "birth-weight-percentile",
    "Birth Weight Centile",
    "obstetrics-pediatrics",
    "Centile proxy",
    "Birth weight centile proxy.",
    [{ key: "bw_g", label: "Birth weight (g)", fieldType: "NUMBER", min: 500, max: 6000, defaultValue: 3300 }],
    [out("Birth Weight Centile", "", "bw_centile_proxy", 2)]
  ),
  calc(
    "pregnancy-weight-gain",
    "Pregnancy Weight Gain",
    "obstetrics-pediatrics",
    "Total gain",
    "Weight gain during pregnancy.",
    [{ shared: "weight-kg" }, { key: "current_weight", label: "Current weight (kg)", fieldType: "NUMBER", min: 40, max: 150, defaultValue: 75 }, { key: "pre_pregnancy", label: "Pre-pregnancy weight (kg)", fieldType: "NUMBER", min: 40, max: 150, defaultValue: 65 }],
    [out("Pregnancy Weight Gain", "kg", "current_weight - pre_pregnancy", 2)]
  ),
  calc(
    "nihss-proxy",
    "NIHSS Proxy",
    "neurology",
    "Stroke scale",
    "Stroke severity proxy.",
    [],
    [out("NIHSS Proxy", "points", "nihss_points", 2)]
  ),
  calc(
    "gcs",
    "Glasgow Coma Scale",
    "neurology",
    "GCS",
    "Consciousness level.",
    [{ key: "eye", label: "Eye", fieldType: "NUMBER", min: 1, max: 4, defaultValue: 4 }, { key: "verbal", label: "Verbal", fieldType: "NUMBER", min: 1, max: 5, defaultValue: 5 }, { key: "motor", label: "Motor", fieldType: "NUMBER", min: 1, max: 6, defaultValue: 6 }],
    [out("Glasgow Coma Scale", "", "eye + verbal + motor", 2)]
  ),
  calc(
    "ich-volume",
    "ICH Volume",
    "neurology",
    "ABC/2",
    "Intracerebral hemorrhage volume.",
    [{ key: "a", label: "Length A (cm)", fieldType: "NUMBER", min: 0.1, max: 10, defaultValue: 4 }, { key: "b", label: "Length B (cm)", fieldType: "NUMBER", min: 0.1, max: 10, defaultValue: 3 }, { key: "c", label: "Length C (cm)", fieldType: "NUMBER", min: 0.1, max: 10, defaultValue: 3 }],
    [out("ICH Volume", "mL", "abc_volume", 2)]
  ),
  calc(
    "hunt-hess",
    "Hunt and Hess Grade",
    "neurology",
    "SAH",
    "Subarachnoid hemorrhage grade proxy.",
    [],
    [out("Hunt and Hess Grade", "", "hh_grade", 2)]
  ),
  calc(
    "fisher-grade",
    "Fisher Grade",
    "neurology",
    "SAH CT",
    "Vasospasm risk on CT (proxy).",
    [],
    [out("Fisher Grade", "", "fisher_grade", 2)]
  ),
  calc(
    "abcd2",
    "ABCD2 Score",
    "neurology",
    "TIA risk",
    "Stroke risk after TIA (simplified).",
    [{ shared: "age-years" }, { shared: "sbp" }],
    [out("ABCD2 Score", "points", "abcd2_points", 2)]
  ),
  calc(
    "canadian-ct-head",
    "Canadian CT Head Rule",
    "neurology",
    "CT need",
    "Minor head injury CT rule proxy.",
    [{ shared: "age-years" }],
    [out("Canadian CT Head Rule", "", "ct_rule_positive", 2)]
  ),
  calc(
    "west-haven",
    "West Haven Criteria",
    "neurology",
    "HE grade",
    "Hepatic encephalopathy grade proxy.",
    [],
    [out("West Haven Criteria", "", "wh_grade", 2)]
  ),
  calc(
    "ciwa-ar",
    "CIWA-Ar Proxy",
    "neurology",
    "Alcohol withdrawal",
    "Withdrawal severity proxy.",
    [],
    [out("CIWA-Ar Proxy", "points", "ciwa_points", 2)]
  ),
  calc(
    "bisap",
    "BISAP Score",
    "neurology",
    "Pancreatitis",
    "Pancreatitis mortality score (simplified).",
    [{ shared: "age-years" }],
    [out("BISAP Score", "points", "bisap_points", 2)]
  ),
  calc(
    "ranson-gcs",
    "Ranson + GCS",
    "neurology",
    "Combined",
    "Combined severity education.",
    [{ key: "ranson_points", label: "Ranson points", fieldType: "NUMBER", min: 0, max: 11, defaultValue: 2 }, { key: "gcs", label: "GCS", fieldType: "NUMBER", min: 3, max: 15, defaultValue: 15 }],
    [out("Ranson + GCS", "points", "ranson_points + (15 - gcs)", 2)]
  ),
  calc(
    "stroke-volume-brain",
    "Cerebral Perfusion Pressure",
    "neurology",
    "CPP",
    "CPP = MAP − ICP.",
    [{ shared: "systolic-bp" }, { shared: "diastolic-bp" }, { key: "icp", label: "ICP (mmHg)", fieldType: "NUMBER", min: 0, max: 40, defaultValue: 15 }],
    [out("Cerebral Perfusion Pressure", "mmHg", "(sbp + 2 * dbp) / 3 - icp", 2)]
  ),
  calc(
    "mrs",
    "Modified Rankin Scale",
    "neurology",
    "mRS",
    "Functional outcome scale entry.",
    [{ key: "mrs", label: "mRS (0-6)", fieldType: "NUMBER", min: 0, max: 6, defaultValue: 1 }],
    [out("Modified Rankin Scale", "", "mrs", 2)]
  ),
  calc(
    "bsa-mosteller",
    "BSA for Chemotherapy",
    "oncology-supportive",
    "Mosteller",
    "Body surface area for chemo dosing.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }],
    [out("BSA for Chemotherapy", "m²", "sqrt(height_cm * weight_kg / 3600)", 2)]
  ),
  calc(
    "carboplatin-calvert",
    "Carboplatin AUC",
    "oncology-supportive",
    "Calvert",
    "Carboplatin dosing by AUC.",
    [{ shared: "age-years" }, { shared: "weight-kg" }, { shared: "sex-mf" }, { shared: "serum-creatinine" }, { key: "auc", label: "Target AUC", fieldType: "NUMBER", min: 1, max: 8, defaultValue: 5 }, { key: "gfr", label: "GFR (mL/min)", fieldType: "NUMBER", min: 10, max: 150, defaultValue: 90 }],
    [out("Carboplatin AUC", "mg", "auc * (gfr + 25)", 2)]
  ),
  calc(
    "karnofsky",
    "Karnofsky Score",
    "oncology-supportive",
    "KPS",
    "Performance status percent.",
    [{ key: "kps", label: "KPS (0-100)", fieldType: "NUMBER", min: 0, max: 100, defaultValue: 80 }],
    [out("Karnofsky Score", "%", "kps", 2)]
  ),
  calc(
    "ecog",
    "ECOG Performance Status",
    "oncology-supportive",
    "ECOG",
    "Eastern Cooperative Oncology Group status.",
    [{ key: "ecog", label: "ECOG (0-5)", fieldType: "NUMBER", min: 0, max: 5, defaultValue: 1 }],
    [out("ECOG Performance Status", "", "ecog", 2)]
  ),
  calc(
    "opioid-conversion",
    "Opioid Conversion",
    "oncology-supportive",
    "MME",
    "Morphine milligram equivalents.",
    [],
    [out("Opioid Conversion", "MME/day", "mme_total", 2)]
  ),
  calc(
    "chemo-bsa-dose",
    "Chemo Dose by BSA",
    "oncology-supportive",
    "mg/m²",
    "BSA-based chemotherapy dose.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }, { key: "dose_m2", label: "Dose mg/m²", fieldType: "NUMBER", min: 1, max: 500, defaultValue: 75 }],
    [out("Chemo Dose by BSA", "mg", "dose_m2 * sqrt(height_cm * weight_kg / 3600)", 2)]
  ),
  calc(
    "neutropenic-fever-risk",
    "Febrile Neutropenia Risk",
    "oncology-supportive",
    "ANC threshold",
    "ANC below threshold flag.",
    [{ shared: "wbc" }, { key: "neut_pct", label: "Neutrophil %", fieldType: "NUMBER", min: 0, max: 100, defaultValue: 50 }, { key: "anc_threshold", label: "ANC threshold", fieldType: "NUMBER", min: 100, max: 2000, defaultValue: 500 }],
    [out("Febrile Neutropenia Risk", "", "wbc * 1000 * neut_pct / 100 < anc_threshold", 2)]
  ),
  calc(
    "fluid-allowance",
    "Daily Fluid Allowance",
    "oncology-supportive",
    "Oncology fluids",
    "Maintenance fluids in oncology.",
    [{ shared: "weight-kg" }],
    [out("Daily Fluid Allowance", "mL", "weight_kg * 30", 2)]
  ),
  calc(
    "albumin-oncology",
    "Albumin Correction",
    "oncology-supportive",
    "Nutrition",
    "Oncology nutrition marker.",
    [{ shared: "albumin" }],
    [out("Albumin Correction", "g/dL", "albumin", 2)]
  ),
  calc(
    "corrected-calcium-onc",
    "Corrected Calcium",
    "oncology-supportive",
    "Oncology Ca",
    "Corrected calcium in malignancy.",
    [{ shared: "measured-calcium" }, { shared: "albumin" }],
    [out("Corrected Calcium", "mg/dL", "measured_ca + 0.8 * (4 - albumin)", 2)]
  ),
  calc(
    "tls-risk",
    "Tumor Lysis Risk",
    "oncology-supportive",
    "TLS proxy",
    "Tumor lysis syndrome risk proxy.",
    [{ shared: "potassium" }, { shared: "phosphate" }, { shared: "uric-acid" }, { key: "phosphate", label: "Phosphate", fieldType: "NUMBER", min: 1, max: 15, defaultValue: 3.5 }, { key: "uric-acid", label: "Uric acid", fieldType: "NUMBER", min: 1, max: 20, defaultValue: 5 }],
    [out("Tumor Lysis Risk", "points", "tls_points", 2)]
  ),
  calc(
    "bsa-du-bois",
    "BSA Du Bois",
    "oncology-supportive",
    "Du Bois",
    "Alternative BSA formula.",
    [{ shared: "height-cm" }, { shared: "weight-kg" }],
    [out("BSA Du Bois", "m²", "0.20247 * (height_cm / 100) ^ 0.725 * weight_kg ^ 0.425", 2)]
  ),
  calc(
    "qtc-fredericia",
    "Corrected QT (Fridericia)",
    "cardiology",
    "QTc = QT / RR^(1/3)",
    "QT interval corrected with Fridericia.",
    [{ key: "heart_rate", label: "Heart rate (bpm)", fieldType: "NUMBER", min: 30, max: 220, defaultValue: 72 }, { key: "qt_ms", label: "QT interval (ms)", fieldType: "NUMBER", min: 200, max: 600, defaultValue: 400 }],
    [out("Corrected QT (Fridericia)", "ms", "qt_ms / (60 / heart_rate) ^ (1/3)", 2)]
  ),
  calc(
    "qtc-framingham",
    "Corrected QT (Framingham)",
    "cardiology",
    "QTc = QT + 0.154×(1−RR)",
    "Alternative QT correction formula.",
    [{ key: "heart_rate", label: "Heart rate (bpm)", fieldType: "NUMBER", min: 30, max: 220, defaultValue: 72 }, { key: "qt_ms", label: "QT interval (ms)", fieldType: "NUMBER", min: 200, max: 600, defaultValue: 400 }],
    [out("Corrected QT (Framingham)", "ms", "qt_ms + 154 * (1 - 60 / heart_rate)", 2)]
  ),
  calc(
    "diastolic-dysfunction-proxy",
    "E/e′ Ratio",
    "cardiology",
    "E/e′",
    "Diastolic function estimate from echo indices.",
    [{ key: "heart_rate", label: "Heart rate (bpm)", fieldType: "NUMBER", min: 30, max: 220, defaultValue: 72 }, { key: "e_velocity", label: "E velocity (cm/s)", fieldType: "NUMBER", min: 20, max: 200, defaultValue: 80 }, { key: "e_prime", label: "e′ velocity (cm/s)", fieldType: "NUMBER", min: 2, max: 25, defaultValue: 10 }],
    [out("E/e′ Ratio", "", "e_velocity / e_prime", 2)]
  ),
  calc(
    "urea-reduction-ratio",
    "Urea Reduction Ratio",
    "nephrology",
    "URR",
    "Dialysis adequacy from pre/post BUN.",
    [{ key: "urea_pre", label: "Pre-dialysis BUN", fieldType: "NUMBER", min: 10, max: 200, defaultValue: 80 }, { key: "urea_post", label: "Post-dialysis BUN", fieldType: "NUMBER", min: 5, max: 100, defaultValue: 20 }],
    [out("Urea Reduction Ratio", "%", "100 * (1 - urea_post / urea_pre)", 2)]
  ),
  calc(
    "creatinine-height-index",
    "Creatinine Height Index",
    "nephrology",
    "CHI",
    "Muscle mass screening in CKD.",
    [{ shared: "height-cm" }, { shared: "serum-creatinine" }],
    [out("Creatinine Height Index", "", "((140 - age) * height_cm / (72 * scr)) / height_cm", 2)]
  ),
  calc(
    "horowitz-index",
    "Horowitz Index (PAFI)",
    "pulmonology",
    "PaO₂/FiO₂",
    "Oxygenation index for ARDS classification.",
    [{ shared: "pao2" }, { shared: "fio2-percent" }],
    [out("Horowitz Index (PAFI)", "mmHg", "pao2 / (fio2 / 100)", 2)]
  ),
  calc(
    "respiratory-quotient",
    "Respiratory Quotient",
    "pulmonology",
    "RQ = VCO₂/VO₂",
    "Metabolic substrate utilization index.",
    [{ key: "vco2", label: "VCO₂ (mL/min)", fieldType: "NUMBER", min: 50, max: 3000, defaultValue: 200 }, { key: "vo2", label: "VO₂ (mL/min)", fieldType: "NUMBER", min: 50, max: 3000, defaultValue: 250 }],
    [out("Respiratory Quotient", "", "vco2 / vo2", 2)]
  ),
  calc(
    "absolute-lymphocyte-count",
    "Absolute Lymphocyte Count",
    "hematology",
    "ALC",
    "Lymphocyte count from WBC percentage.",
    [{ shared: "wbc" }, { key: "lymph_pct", label: "Lymphocyte %", fieldType: "NUMBER", min: 0, max: 100, defaultValue: 30 }],
    [out("Absolute Lymphocyte Count", "/µL", "wbc * 1000 * lymph_pct / 100", 2)]
  ),
  calc(
    "absolute-eosinophil-count",
    "Absolute Eosinophil Count",
    "hematology",
    "AEC",
    "Eosinophil count from WBC percentage.",
    [{ shared: "wbc" }, { key: "eos_pct", label: "Eosinophil %", fieldType: "NUMBER", min: 0, max: 100, defaultValue: 2 }],
    [out("Absolute Eosinophil Count", "/µL", "wbc * 1000 * eos_pct / 100", 2)]
  ),
  calc(
    "homa-beta",
    "HOMA-Beta",
    "endocrinology",
    "Beta-cell function",
    "Beta-cell function estimate.",
    [{ key: "insulin", label: "Fasting insulin (µIU/mL)", fieldType: "NUMBER", min: 1, max: 100, defaultValue: 10 }],
    [out("HOMA-Beta", "", "20 * insulin / (glucose - 3.5)", 2)]
  ),
  calc(
    "protein-percent-calories",
    "Protein Percent of Calories",
    "nutrition-diet",
    "% kcal from protein",
    "Percent of total calories from protein grams.",
    [{ key: "protein_g", label: "Protein (g)", fieldType: "NUMBER", min: 20, max: 400, defaultValue: 100 }, { key: "total_kcal", label: "Total calories", fieldType: "NUMBER", min: 800, max: 5000, defaultValue: 2000 }],
    [out("Protein Percent of Calories", "%", "100 * protein_g * 4 / total_kcal", 2)]
  ),
  calc(
    "alcohol-calories",
    "Alcohol Calories",
    "nutrition-diet",
    "kcal from ethanol",
    "Calories contributed by alcoholic beverages.",
    [{ key: "ethanol_g", label: "Ethanol (grams)", fieldType: "NUMBER", min: 0, max: 200, defaultValue: 14 }],
    [out("Alcohol Calories", "kcal", "ethanol_g * 7", 2)]
  ),
  calc(
    "pediatric-dose-clark",
    "Pediatric Dose (Clark)",
    "pharmacology",
    "Weight-based fraction",
    "Clark rule pediatric dose estimate.",
    [{ shared: "weight-kg" }, { key: "adult_dose", label: "Adult dose (mg)", fieldType: "NUMBER", min: 1, max: 2000, defaultValue: 500 }],
    [out("Pediatric Dose (Clark)", "mg", "adult_dose * weight_kg / 70", 2)]
  ),
  calc(
    "aminoglycoside-interval",
    "Extended Interval Aminoglycoside",
    "pharmacology",
    "Hartford nomogram helper",
    "Peak-based interval suggestion (educational).",
    [{ key: "peak", label: "Peak level (µg/mL)", fieldType: "NUMBER", min: 10, max: 80, defaultValue: 55 }],
    [out("Extended Interval Aminoglycoside", "hours", "peak > 60 ? 24 : peak > 50 ? 36 : 48", 2)]
  ),
  calc(
    "bishop-score",
    "Bishop Score",
    "obstetrics-pediatrics",
    "Cervical readiness",
    "Labor induction readiness score.",
    [{ key: "dilation", label: "Dilation (0-3)", fieldType: "NUMBER", min: 0, max: 3, defaultValue: 1 }, { key: "effacement", label: "Effacement (0-3)", fieldType: "NUMBER", min: 0, max: 3, defaultValue: 1 }, { key: "station", label: "Station (0-3)", fieldType: "NUMBER", min: 0, max: 3, defaultValue: 1 }, { key: "consistency", label: "Consistency (0-2)", fieldType: "NUMBER", min: 0, max: 2, defaultValue: 1 }, { key: "position", label: "Position (0-2)", fieldType: "NUMBER", min: 0, max: 2, defaultValue: 1 }],
    [out("Bishop Score", "points", "dilation + effacement + station + consistency + position", 2)]
  ),
  calc(
    "glasgow-pupils-score",
    "GCS-Pupils Score",
    "neurology",
    "GCS-P",
    "Combines GCS with pupil reactivity (simplified).",
    [{ shared: "gcs" }, { key: "pupil_score", label: "Pupil score (0-2)", fieldType: "NUMBER", min: 0, max: 2, defaultValue: 2 }],
    [out("GCS-Pupils Score", "points", "gcs + pupil_score", 2)]
  ),
  calc(
    "steroid-cross-equiv",
    "Dexamethasone Equivalence",
    "oncology-supportive",
    "Steroid conversion",
    "Convert dexamethasone dose to prednisone equivalent.",
    [{ key: "dex_mg", label: "Dexamethasone (mg)", fieldType: "NUMBER", min: 0.5, max: 40, defaultValue: 4 }],
    [out("Dexamethasone Equivalence", "mg prednisone equiv", "dex_mg * 6.7", 2)]
  )];
