import { FieldType } from "@prisma/client";
import type { SeedSharedField } from "./types";

const sexOptions = [
  { label: "Male", value: 1 },
  { label: "Female", value: 0 },
];

const activityOptions = [
  { label: "Sedentary (1.2)", value: 1.2 },
  { label: "Lightly active (1.375)", value: 1.375 },
  { label: "Moderately active (1.55)", value: 1.55 },
  { label: "Very active (1.725)", value: 1.725 },
  { label: "Extra active (1.9)", value: 1.9 },
];

export const seedSharedFields: SeedSharedField[] = [
  {
    slug: "height-cm",
    key: "height_cm",
    label: "Height",
    fieldType: FieldType.NUMBER,
    min: 50,
    max: 250,
    step: 0.1,
    defaultValue: 170,
    unitPresetSlug: "length-stored-as-cm",
  },
  {
    slug: "weight-kg",
    key: "weight_kg",
    label: "Weight",
    fieldType: FieldType.NUMBER,
    min: 1,
    max: 350,
    step: 0.1,
    defaultValue: 70,
    unitPresetSlug: "mass-stored-as-kg",
  },
  {
    slug: "age-years",
    key: "age",
    label: "Age",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 120,
    step: 1,
    defaultValue: 40,
  },
  {
    slug: "sex-mf",
    key: "sex",
    label: "Sex",
    fieldType: FieldType.SELECT,
    defaultValue: 1,
    selectOptions: sexOptions,
  },
  {
    slug: "sbp",
    key: "sbp",
    label: "Systolic blood pressure",
    fieldType: FieldType.NUMBER,
    min: 60,
    max: 280,
    step: 1,
    defaultValue: 120,
    unitPresetSlug: "blood-pressure-mmhg",
  },
  {
    slug: "systolic-bp",
    key: "sbp",
    label: "Systolic blood pressure",
    fieldType: FieldType.NUMBER,
    min: 60,
    max: 280,
    step: 1,
    defaultValue: 120,
    unitPresetSlug: "blood-pressure-mmhg",
  },
  {
    slug: "diastolic-bp",
    key: "dbp",
    label: "Diastolic blood pressure",
    fieldType: FieldType.NUMBER,
    min: 30,
    max: 180,
    step: 1,
    defaultValue: 80,
    unitPresetSlug: "blood-pressure-mmhg",
  },
  {
    slug: "heart-rate",
    key: "heart_rate",
    label: "Heart rate",
    fieldType: FieldType.NUMBER,
    min: 20,
    max: 220,
    step: 1,
    defaultValue: 72,
  },
  {
    slug: "resting-hr",
    key: "resting_hr",
    label: "Resting heart rate",
    fieldType: FieldType.NUMBER,
    min: 30,
    max: 120,
    step: 1,
    defaultValue: 65,
  },
  {
    slug: "waist-cm",
    key: "waist_cm",
    label: "Waist circumference",
    fieldType: FieldType.NUMBER,
    min: 40,
    max: 200,
    step: 0.5,
    defaultValue: 85,
    unitPresetSlug: "length-stored-as-cm",
  },
  {
    slug: "neck-cm",
    key: "neck_cm",
    label: "Neck circumference",
    fieldType: FieldType.NUMBER,
    min: 20,
    max: 80,
    step: 0.5,
    defaultValue: 38,
    unitPresetSlug: "length-stored-as-cm",
  },
  {
    slug: "hip-cm",
    key: "hip_cm",
    label: "Hip circumference",
    fieldType: FieldType.NUMBER,
    min: 50,
    max: 200,
    step: 0.5,
    defaultValue: 98,
    unitPresetSlug: "length-stored-as-cm",
  },
  {
    slug: "serum-creatinine",
    key: "scr",
    label: "Serum creatinine",
    fieldType: FieldType.NUMBER,
    min: 0.2,
    max: 20,
    step: 0.01,
    defaultValue: 1,
    unitPresetSlug: "concentration-mg-dl",
  },
  {
    slug: "sodium",
    key: "na",
    label: "Sodium",
    fieldType: FieldType.NUMBER,
    min: 100,
    max: 180,
    step: 1,
    defaultValue: 140,
    unitPresetSlug: "electrolyte-meq-l",
  },
  {
    slug: "chloride",
    key: "cl",
    label: "Chloride",
    fieldType: FieldType.NUMBER,
    min: 70,
    max: 130,
    step: 1,
    defaultValue: 103,
    unitPresetSlug: "electrolyte-meq-l",
  },
  {
    slug: "bicarbonate",
    key: "hco3",
    label: "Bicarbonate",
    fieldType: FieldType.NUMBER,
    min: 5,
    max: 45,
    step: 1,
    defaultValue: 24,
    unitPresetSlug: "electrolyte-meq-l",
  },
  {
    slug: "potassium",
    key: "k",
    label: "Potassium",
    fieldType: FieldType.NUMBER,
    min: 2,
    max: 8,
    step: 0.1,
    defaultValue: 4,
    unitPresetSlug: "electrolyte-meq-l",
  },
  {
    slug: "albumin",
    key: "albumin",
    label: "Albumin",
    fieldType: FieldType.NUMBER,
    min: 1,
    max: 6,
    step: 0.1,
    defaultValue: 4,
    unitPresetSlug: "concentration-g-dl",
  },
  {
    slug: "measured-calcium",
    key: "measured_ca",
    label: "Measured total calcium",
    fieldType: FieldType.NUMBER,
    min: 4,
    max: 20,
    step: 0.1,
    defaultValue: 9.2,
    unitPresetSlug: "concentration-mg-dl",
  },
  {
    slug: "glucose",
    key: "glucose",
    label: "Blood glucose",
    fieldType: FieldType.NUMBER,
    min: 20,
    max: 600,
    step: 1,
    defaultValue: 95,
    unitPresetSlug: "concentration-mg-dl",
  },
  {
    slug: "bun",
    key: "bun",
    label: "Blood urea nitrogen",
    fieldType: FieldType.NUMBER,
    min: 2,
    max: 150,
    step: 1,
    defaultValue: 15,
    unitPresetSlug: "concentration-mg-dl",
  },
  {
    slug: "hemoglobin",
    key: "hb",
    label: "Hemoglobin",
    fieldType: FieldType.NUMBER,
    min: 3,
    max: 22,
    step: 0.1,
    defaultValue: 14,
    unitPresetSlug: "concentration-g-dl",
  },
  {
    slug: "hematocrit",
    key: "hct",
    label: "Hematocrit",
    fieldType: FieldType.NUMBER,
    min: 10,
    max: 70,
    step: 0.1,
    defaultValue: 42,
  },
  {
    slug: "plt",
    key: "plt",
    label: "Platelet count",
    fieldType: FieldType.NUMBER,
    min: 5,
    max: 1000,
    step: 1,
    defaultValue: 250,
  },
  {
    slug: "platelet-count",
    key: "plt",
    label: "Platelet count",
    fieldType: FieldType.NUMBER,
    min: 5,
    max: 1000,
    step: 1,
    defaultValue: 250,
  },
  {
    slug: "wbc",
    key: "wbc",
    label: "White blood cell count",
    fieldType: FieldType.NUMBER,
    min: 0.5,
    max: 50,
    step: 0.1,
    defaultValue: 7,
  },
  {
    slug: "inr",
    key: "inr",
    label: "INR",
    fieldType: FieldType.NUMBER,
    min: 0.5,
    max: 10,
    step: 0.01,
    defaultValue: 1,
  },
  {
    slug: "body-temperature",
    key: "temp_c",
    label: "Body temperature",
    fieldType: FieldType.NUMBER,
    min: 32,
    max: 43,
    step: 0.1,
    defaultValue: 37,
    unitPresetSlug: "temperature-celsius",
  },
  {
    slug: "fio2-percent",
    key: "fio2",
    label: "FiO₂",
    fieldType: FieldType.NUMBER,
    min: 21,
    max: 100,
    step: 1,
    defaultValue: 21,
  },
  {
    slug: "pao2",
    key: "pao2",
    label: "PaO₂",
    fieldType: FieldType.NUMBER,
    min: 30,
    max: 500,
    step: 1,
    defaultValue: 95,
  },
  {
    slug: "paco2",
    key: "paco2",
    label: "PaCO₂",
    fieldType: FieldType.NUMBER,
    min: 15,
    max: 100,
    step: 1,
    defaultValue: 40,
  },
  {
    slug: "ph-arterial",
    key: "ph",
    label: "Arterial pH",
    fieldType: FieldType.NUMBER,
    min: 6.8,
    max: 7.8,
    step: 0.01,
    defaultValue: 7.4,
  },
  {
    slug: "activity-factor",
    key: "activity",
    label: "Physical activity level",
    fieldType: FieldType.SELECT,
    defaultValue: 1.375,
    selectOptions: activityOptions,
  },
  {
    slug: "bilirubin",
    key: "bilirubin",
    label: "Total bilirubin",
    fieldType: FieldType.NUMBER,
    min: 0.1,
    max: 40,
    step: 0.1,
    defaultValue: 0.8,
    unitPresetSlug: "concentration-mg-dl",
  },
  {
    slug: "total-bilirubin",
    key: "bilirubin",
    label: "Total bilirubin",
    fieldType: FieldType.NUMBER,
    min: 0.1,
    max: 40,
    step: 0.1,
    defaultValue: 0.8,
    unitPresetSlug: "concentration-mg-dl",
  },
  {
    slug: "ast",
    key: "ast",
    label: "AST",
    fieldType: FieldType.NUMBER,
    min: 5,
    max: 5000,
    step: 1,
    defaultValue: 25,
  },
  {
    slug: "alt",
    key: "alt",
    label: "ALT",
    fieldType: FieldType.NUMBER,
    min: 5,
    max: 5000,
    step: 1,
    defaultValue: 28,
  },
  {
    slug: "urine-output-ml",
    key: "urine_ml",
    label: "Urine output",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 5000,
    step: 10,
    defaultValue: 800,
    unitPresetSlug: "volume-ml",
  },
  {
    slug: "fluid-intake-ml",
    key: "fluid_ml",
    label: "Fluid intake",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 10000,
    step: 50,
    defaultValue: 2000,
    unitPresetSlug: "volume-ml",
  },
  {
    slug: "respiratory-rate",
    key: "rr",
    label: "Respiratory rate",
    fieldType: FieldType.NUMBER,
    min: 4,
    max: 60,
    step: 1,
    defaultValue: 16,
  },
  {
    slug: "gcs",
    key: "gcs",
    label: "Glasgow Coma Scale (total)",
    fieldType: FieldType.NUMBER,
    min: 3,
    max: 15,
    step: 1,
    defaultValue: 15,
  },
  {
    slug: "hb",
    key: "hb",
    label: "Hemoglobin",
    fieldType: FieldType.NUMBER,
    min: 3,
    max: 22,
    step: 0.1,
    defaultValue: 14,
    unitPresetSlug: "concentration-g-dl",
  },
  {
    slug: "phosphate",
    key: "phosphate",
    label: "Serum phosphate",
    fieldType: FieldType.NUMBER,
    min: 1,
    max: 15,
    step: 0.1,
    defaultValue: 3.5,
    unitPresetSlug: "concentration-mg-dl",
  },
  {
    slug: "uric-acid",
    key: "uric_acid",
    label: "Uric acid",
    fieldType: FieldType.NUMBER,
    min: 1,
    max: 20,
    step: 0.1,
    defaultValue: 5,
    unitPresetSlug: "concentration-mg-dl",
  },
  {
    slug: "urine-osm",
    key: "urine_osm",
    label: "Urine osmolality",
    fieldType: FieldType.NUMBER,
    min: 50,
    max: 1200,
    step: 1,
    defaultValue: 500,
  },
  {
    slug: "serum-osm",
    key: "serum_osm",
    label: "Serum osmolality",
    fieldType: FieldType.NUMBER,
    min: 250,
    max: 350,
    step: 1,
    defaultValue: 290,
  },
  {
    slug: "urine-na",
    key: "urine_na",
    label: "Urine sodium",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 200,
    step: 1,
    defaultValue: 50,
    unitPresetSlug: "electrolyte-meq-l",
  },
  {
    slug: "urine-k",
    key: "urine_k",
    label: "Urine potassium",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 100,
    step: 1,
    defaultValue: 25,
    unitPresetSlug: "electrolyte-meq-l",
  },
  {
    slug: "urine-cl",
    key: "urine_cl",
    label: "Urine chloride",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 200,
    step: 1,
    defaultValue: 50,
    unitPresetSlug: "electrolyte-meq-l",
  },
  {
    slug: "neut_pct",
    key: "neut_pct",
    label: "Neutrophil percentage",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 100,
    step: 0.1,
    defaultValue: 60,
  },
  {
    slug: "neut-pct",
    key: "neut_pct",
    label: "Neutrophil percentage",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 100,
    step: 0.1,
    defaultValue: 60,
  },
  {
    slug: "nRBC",
    key: "nRBC",
    label: "Nucleated RBCs per 100 WBC",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 50,
    step: 0.1,
    defaultValue: 0,
  },
  {
    slug: "nrbc",
    key: "nRBC",
    label: "Nucleated RBCs per 100 WBC",
    fieldType: FieldType.NUMBER,
    min: 0,
    max: 50,
    step: 0.1,
    defaultValue: 0,
  },
  {
    slug: "rdw",
    key: "rdw",
    label: "Red cell distribution width",
    fieldType: FieldType.NUMBER,
    min: 10,
    max: 25,
    step: 0.1,
    defaultValue: 13,
  },
  {
    slug: "rbc-millions",
    key: "rbc_millions",
    label: "RBC count (millions/µL)",
    fieldType: FieldType.NUMBER,
    min: 2,
    max: 8,
    step: 0.01,
    defaultValue: 4.5,
  },
];
